import "dotenv/config";
import { PrismaClient } from "@prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";
import pg from "pg";

const connectionString = process.env.DATABASE_URL;
const pool = new pg.Pool({ connectionString });
const adapter = new PrismaPg(pool);
const prisma = new PrismaClient({ adapter });

const programsData = [
  {
    title: "SSP (Summer Science Program)",
    university: "SSP International",
    location: "Various (US)",
    country: "USA",
    level: "High School",
    category: "Research",
    fields: ["STEM", "Mathematics"],
    format: "Offline",
    duration: "6 Weeks",
    tuition: 0,
    tags: ["Astrophysics", "Biochemistry", "Genomics"],
    eligibility: ["International", "Domestic"],
    description: "A legacy program focusing on collaborative research in Astrophysics, Biochemistry, or Genomics. Students work in teams of three to complete a real-world research project.",
    specialFeatures: ["Collaborative team research", "PhD faculty mentorship", "Legacy alumni network"],
    noticableFacts: ["One of the oldest summer programs", "Hands-on data collection", "High selectivity"],
    applyLink: "https://summerscience.org",
    featured: true
  },
  {
    title: "Lumiere Research Scholar Program",
    university: "Lumiere Education",
    location: "Online / Global",
    country: "USA",
    level: "High School",
    category: "Research",
    fields: ["STEM", "Humanities", "Interdisciplinary"],
    format: "Online",
    duration: "12 Weeks",
    tuition: 3950,
    tags: ["Mentorship", "Research Paper", "PhD"],
    eligibility: ["International", "Domestic"],
    description: "Provides 1-on-1 mentorship with PhD researchers from top-tier universities. It is highly flexible and focuses on producing a high-quality, independent research paper.",
    specialFeatures: ["1-on-1 PhD mentorship", "Individual research paper", "Flexible start dates"],
    noticableFacts: ["Produces publishable quality work", "Mentors from Ivy League schools"],
    applyLink: "https://lumiere-education.com",
  },
  {
    title: "Pioneer Academics",
    university: "Pioneer Academics",
    location: "Online / Global",
    country: "USA",
    level: "High School",
    category: "Research",
    fields: ["STEM", "Humanities", "Business"],
    format: "Online",
    duration: "10 Weeks",
    tuition: 6000,
    tags: ["Credit", "Oberlin", "Research"],
    eligibility: ["International", "Domestic"],
    description: "A global online research institute known for its high standards and partnership with Oberlin College to offer academic credit.",
    specialFeatures: ["Oberlin College credit", "Standardized research process", "Diverse subject areas"],
    noticableFacts: ["First online research program for HS", "Strict evaluation metrics"],
    applyLink: "https://pioneeracademics.com",
  },
  {
    title: "PROMYS / ROSS / HCSSiM",
    university: "Boston Univ / Ohio State",
    location: "MA & OH",
    country: "USA",
    level: "High School",
    category: "Summer",
    fields: ["Mathematics"],
    format: "Offline",
    duration: "6 Weeks",
    tuition: 0,
    tags: ["Number Theory", "Math Camp", "Selective"],
    eligibility: ["International", "Domestic"],
    description: "The 'Holy Trinity' of math camps focusing on deep number theory and mathematical logic. They look for 'mathematical maturity.'",
    specialFeatures: ["Proof-based learning", "Legendary problem sets", "Immersion in math culture"],
    noticableFacts: ["Low acceptance rates", "Highly regarded by top colleges"],
    applyLink: "https://promys.org",
  },
  {
    title: "Honors Summer Math Camp (HSMC)",
    university: "Texas State University",
    location: "San Marcos, TX",
    country: "USA",
    level: "High School",
    category: "Research",
    fields: ["Mathematics", "STEM"],
    format: "Offline",
    duration: "6 Weeks",
    tuition: 0,
    tags: ["Research", "Math", "Residential"],
    eligibility: ["International", "Domestic"],
    description: "A residential program that emphasizes developing creative and critical thinking through math research projects.",
    specialFeatures: ["Team research projects", "Creative problem solving", "Social activities"],
    noticableFacts: ["Focus on 'mathematical thinking'", "Long-standing tradition"],
    applyLink: "https://txstate.edu/hsmc",
  },
  {
    title: "TechGirls",
    university: "U.S. Dept of State",
    location: "Washington D.C. + Hybrid",
    country: "USA",
    level: "High School",
    category: "Summer",
    fields: ["STEM", "Interdisciplinary"],
    format: "Hybrid",
    duration: "4 Weeks",
    tuition: 0,
    tags: ["Leadership", "Girls in STEM", "Exchange"],
    eligibility: ["International"],
    description: "An exchange program for young women in STEM focusing on tech-leadership and community action projects.",
    specialFeatures: ["Fully funded exchange", "Industry job shadowing", "Follow-on project support"],
    noticableFacts: ["Covers all travel & board", "Focus on underrepresented regions"],
    applyLink: "https://techgirlsglobal.org",
  },
  {
    title: "Bentley Wall Street 101",
    university: "Bentley University",
    location: "Waltham, MA",
    country: "USA",
    level: "High School",
    category: "Summer",
    fields: ["Business"],
    format: "Offline",
    duration: "1 Week",
    tuition: 1500,
    tags: ["Finance", "Bloomberg", "Trading"],
    eligibility: ["International", "Domestic"],
    description: "An intensive introduction to global finance, stock markets, and investment research using Bloomberg terminals.",
    specialFeatures: ["Bloomberg Terminal access", "Stock pitch competition", "Trading simulations"],
    noticableFacts: ["Professional-grade tools", "Short, high-intensity learning"],
    applyLink: "https://bentley.edu/wallstreet101",
  },
  {
    title: "LaunchX",
    university: "LaunchX Global",
    location: "Various / Online",
    country: "USA",
    level: "High School",
    category: "Summer",
    fields: ["Business", "Interdisciplinary"],
    format: "Hybrid",
    duration: "4 Weeks",
    tuition: 0,
    tags: ["Entrepreneurship", "Startups", "Founder"],
    eligibility: ["International", "Domestic"],
    description: "Rigorous entrepreneurship program where students actually start a company during the summer. Available both in-person and online.",
    specialFeatures: ["Start a real company", "Pitch to investors", "Founding team formation"],
    noticableFacts: ["Focus on action over theory", "Strong startup alumni"],
    applyLink: "https://launchx.com",
  },
  {
    title: "Wharton Global Youth Program",
    university: "UPenn Wharton",
    location: "Philadelphia, PA",
    country: "USA",
    level: "High School",
    category: "Summer",
    fields: ["Business", "STEM"],
    format: "Offline",
    duration: "2-4 Weeks",
    tuition: 5000,
    tags: ["Wharton", "Business", "Leadership"],
    eligibility: ["International", "Domestic"],
    description: "Various tracks like 'Leadership in the Business World' and 'Data Science' hosted at the University of Pennsylvania.",
    specialFeatures: ["Ivy League experience", "Wharton faculty lectures", "Business simulations"],
    noticableFacts: ["Top-tier business networking", "Multiple subject tracks"],
    applyLink: "https://globalyouth.wharton.upenn.edu",
  },
  {
    title: "UWC Short Courses",
    university: "United World Colleges",
    location: "Global",
    country: "Global",
    level: "High School",
    category: "Summer",
    fields: ["Humanities", "Interdisciplinary"],
    format: "Offline",
    duration: "2 Weeks",
    tuition: 1200,
    tags: ["Sustainability", "Peacebuilding", "Culture"],
    eligibility: ["International", "Domestic"],
    description: "Shorter versions of the UWC experience, focusing on sustainability, peacebuilding, and intercultural understanding.",
    specialFeatures: ["Intercultural dialogue", "Experiential learning", "Peacebuilding workshops"],
    noticableFacts: ["Hosted at UWC campuses globally", "Financial aid often available"],
    applyLink: "https://uwc.org/short-courses",
  },
  {
    title: "Yale Young Global Scholars",
    university: "Yale University",
    location: "New Haven, CT",
    country: "USA",
    level: "High School",
    category: "Summer",
    fields: ["STEM", "Humanities", "Business"],
    format: "Offline",
    duration: "2 Weeks",
    tuition: 6500,
    tags: ["Yale", "Leadership", "Global"],
    eligibility: ["International", "Domestic"],
    description: "A world-renowned academic leadership program. Offers tracks ranging from Science & Technology to Politics, Law & Economics.",
    specialFeatures: ["Yale faculty seminars", "Capstone projects", "Global peer community"],
    noticableFacts: ["One of the most diverse programs", "Yale campus residency"],
    applyLink: "https://globalscholars.yale.edu",
  },
  {
    title: "MIT PRIMES (Research in Math)",
    university: "MIT",
    location: "Cambridge, MA",
    country: "USA",
    level: "High School",
    category: "Research",
    fields: ["STEM", "Mathematics"],
    format: "Hybrid",
    duration: "1 Year",
    tuition: 0,
    tags: ["Mathematics", "Research", "Competition"],
    eligibility: ["International", "Domestic"],
    description: "Program for Research in Mathematics, Engineering, and Science for High School Students. Includes individual and group research projects.",
    specialFeatures: ["Mentorship by MIT graduate students", "Advanced math research", "Publication opportunities"],
    noticableFacts: ["Tuition-free", "Highly selective academic track"],
    applyLink: "https://math.mit.edu/primes",
  },
  {
    title: "Stanford Summer Humanities Institute",
    university: "Stanford University",
    location: "Stanford, CA",
    country: "USA",
    level: "High School",
    category: "Summer",
    fields: ["Humanities"],
    format: "Offline",
    duration: "3 Weeks",
    tuition: 0,
    tags: ["Humanities", "Philosophy", "Writing"],
    eligibility: ["International", "Domestic"],
    description: "Explore the big questions of humanity through intensive seminars with Stanford professors in fields like philosophy, history, and literature.",
    specialFeatures: ["Professor-led seminars", "University-level writing", "Residential experience"],
    noticableFacts: ["Financial aid available", "Intensive academic exploration"],
    applyLink: "https://summerhumanities.stanford.edu",
  },
  {
    title: "RSI (Research Science Institute)",
    university: "MIT & CEE",
    location: "Cambridge, MA",
    country: "USA",
    level: "High School",
    category: "Research",
    fields: ["STEM"],
    format: "Offline",
    duration: "6 Weeks",
    tuition: 0,
    tags: ["STEM Research", "Competition", "Cost-Free"],
    eligibility: ["International", "Domestic"],
    description: "The first cost-free to students, summer science & engineering program to combine on-campus course work in scientific theory with off-campus work in science and technology research.",
    specialFeatures: ["Full scholarship", "Research with leading scientists", "Mentorship from MIT/Harvard faculty"],
    noticableFacts: ["Prestigious 'Rickoids' alumni network", "Extremely low acceptance rate"],
    applyLink: "https://cee.org/rsi",
  },
  {
    title: "KAUST Discovery Scholars Program",
    university: "KAUST",
    location: "Thuwal, Saudi Arabia",
    country: "Saudi Arabia",
    level: "Undergraduate",
    category: "Research",
    fields: ["STEM"],
    format: "Offline",
    duration: "8 Weeks",
    tuition: 0,
    tags: ["STEM", "Research", "Fully Funded"],
    eligibility: ["International"],
    description: "A prestigious scholarship and research program for outstanding undergraduate students to experience world-class research at KAUST.",
    specialFeatures: ["Full travel & housing coverage", "Stipend included", "Cutting-edge lab access"],
    noticableFacts: ["Global cohort", "Fast-track to Graduate school"],
    applyLink: "https://kaust.edu.sa",
  },
  {
    title: "QuestBridge College Prep Scholars",
    university: "QuestBridge",
    location: "USA / Online",
    country: "USA",
    level: "High School",
    category: "University",
    fields: ["Interdisciplinary"],
    format: "Hybrid",
    duration: "Summer",
    tuition: 0,
    tags: ["Full Scholarship", "College Prep"],
    eligibility: ["Domestic"],
    description: "Provides high-achieving, low-income students with tools and opportunities to excel in the college admissions process.",
    specialFeatures: ["Full scholarships to summer programs", "Admissions counseling", "QuestBridge network access"],
    noticableFacts: ["Pathway to top-tier universities", "Focus on financial accessibility"],
    applyLink: "https://questbridge.org",
  },
  {
    title: "Carnegie Mellon SAMS",
    university: "Carnegie Mellon University",
    location: "Pittsburgh, PA",
    country: "USA",
    level: "High School",
    category: "Summer",
    fields: ["STEM"],
    format: "Offline",
    duration: "6 Weeks",
    tuition: 0,
    tags: ["STEM", "Full Scholarship"],
    eligibility: ["Domestic"],
    description: "Summer Academy for Math and Science. Provides students from underrepresented backgrounds with the opportunity to explore STEM fields.",
    specialFeatures: ["No cost for tuition/room/board", "Project-based learning", "Mentorship from CMU faculty"],
    noticableFacts: ["Focus on diversity in STEM", "Intensive academic curriculum"],
    applyLink: "https://cmu.edu/pre-college/sams",
  },
  {
    title: "NSF REU",
    university: "National Science Foundation",
    location: "USA",
    country: "USA",
    level: "Undergraduate",
    category: "Research",
    fields: ["STEM"],
    format: "Offline",
    duration: "10 Weeks",
    tuition: 0,
    tags: ["STEM", "Paid", "Funded"],
    eligibility: ["Domestic"],
    description: "Research Experiences for Undergraduates. Supports active research participation by undergraduate students in any of the areas of research funded by the NSF.",
    specialFeatures: ["Stipend provided", "Housing and travel support", "Direct research experience"],
    noticableFacts: ["Thousands of sites across the US", "Critical for PhD applications"],
    applyLink: "https://nsf.gov/reu",
  },
  {
    title: "NASA OSTEM Internships",
    university: "NASA",
    location: "Multiple Sites, USA",
    country: "USA",
    level: "High School",
    category: "Internship",
    fields: ["STEM"],
    format: "Offline",
    duration: "8-10 Weeks",
    tuition: 0,
    tags: ["STEM", "NASA", "Paid"],
    eligibility: ["Domestic"],
    description: "NASA Office of STEM Engagement internships provide students with the opportunity to participate in either research or other experiential learning.",
    specialFeatures: ["Paid internships", "Work at NASA centers", "Real mission involvement"],
    noticableFacts: ["Highly competitive", "Hands-on engineering projects"],
    applyLink: "https://intern.nasa.gov",
  },
  {
    title: "CERN Summer Student Program",
    university: "CERN",
    location: "Geneva, Switzerland",
    country: "Switzerland",
    level: "Undergraduate",
    category: "Summer",
    fields: ["STEM"],
    format: "Offline",
    duration: "8-13 Weeks",
    tuition: 0,
    tags: ["Physics", "Funded"],
    eligibility: ["International"],
    description: "Experience CERN's unique scientific environment. Join a research team and attend lectures by renowned scientists.",
    specialFeatures: ["Stipend included", "Lecture series by experts", "Visits to CERN accelerators"],
    noticableFacts: ["International physics hub", "Largest particle physics lab"],
    applyLink: "https://careers.cern/summer",
  },
  {
    title: "Google Summer of Code",
    university: "Google Open Source",
    location: "Online / Global",
    country: "Global",
    level: "Undergraduate",
    category: "Internship",
    fields: ["STEM"],
    format: "Online",
    duration: "12 Weeks",
    tuition: 0,
    tags: ["Open Source", "Coding", "Stipend"],
    eligibility: ["International", "Domestic"],
    description: "A global, online program focused on bringing new contributors into open source software development.",
    specialFeatures: ["Stipend for contributions", "Work with real OSS orgs", "Expert mentorship"],
    noticableFacts: ["Remote-first", "Highly valued by tech companies"],
    applyLink: "https://summerofcode.withgoogle.com",
  },
  {
    title: "MIT Summer Research Program (MSRP)",
    university: "MIT",
    location: "Cambridge, MA",
    country: "USA",
    level: "Undergraduate",
    category: "Research",
    fields: ["STEM", "Humanities"],
    format: "Offline",
    duration: "9 Weeks",
    tuition: 0,
    tags: ["Research", "Fully Funded", "MIT"],
    eligibility: ["Domestic"],
    description: "MSRP seeks to identify talented sophomores and juniors from across the US who are interested in pursuing a PhD at MIT.",
    specialFeatures: ["Round-trip travel", "University housing", "Weekly stipend"],
    noticableFacts: ["Bridge to MIT PhD", "Intensive faculty-led research"],
    applyLink: "https://oge.mit.edu/msrp",
  },
  {
    title: "Caltech SURF",
    university: "Caltech",
    location: "Pasadena, CA",
    country: "USA",
    level: "Undergraduate",
    category: "Research",
    fields: ["STEM"],
    format: "Offline",
    duration: "10 Weeks",
    tuition: 0,
    tags: ["Research", "STEM", "Paid"],
    eligibility: ["International", "Domestic"],
    description: "Summer Undergraduate Research Fellowships. Introduces students to research under the guidance of Caltech faculty.",
    specialFeatures: ["Direct faculty mentorship", "Oral presentations", "Published technical reports"],
    noticableFacts: ["Prestigious research foundation", "Strong focus on innovation"],
    applyLink: "https://sfp.caltech.edu/surf",
  },
  {
    title: "Stanford CURIS",
    university: "Stanford University",
    location: "Stanford, CA",
    country: "USA",
    level: "Undergraduate",
    category: "Research",
    fields: ["STEM"],
    format: "Offline",
    duration: "10 Weeks",
    tuition: 0,
    tags: ["Computer Science", "Research", "Stipend"],
    eligibility: ["International", "Domestic"],
    description: "Undergraduate Research in Computer Science. Provides Stanford students and visitors with research opportunities in the CS department.",
    specialFeatures: ["AI & Robotics research", "Systems & Networking", "Stipend support"],
    noticableFacts: ["Silicon Valley integration", "Leading-edge CS research"],
    applyLink: "https://cs.stanford.edu/curis",
  },
  {
    title: "Oxford UNIQ Summer School",
    university: "University of Oxford",
    location: "Oxford, UK",
    country: "UK",
    level: "High School",
    category: "Summer",
    fields: ["STEM", "Humanities"],
    format: "Offline",
    duration: "1 Week",
    tuition: 0,
    tags: ["Oxford", "Access", "Free"],
    eligibility: ["Domestic"],
    description: "Gives students from state schools in the UK a chance to experience life at Oxford and learn about the application process.",
    specialFeatures: ["Residential at an Oxford college", "Tutorial-style teaching", "Application support"],
    noticableFacts: ["Free of charge", "Aimed at underrepresented groups"],
    applyLink: "https://uniq.ox.ac.uk",
  },
  {
    title: "Cambridge Sutton Trust Summer School",
    university: "University of Cambridge",
    location: "Cambridge, UK",
    country: "UK",
    level: "High School",
    category: "Summer",
    fields: ["STEM", "Humanities", "Business"],
    format: "Offline",
    duration: "1 Week",
    tuition: 0,
    tags: ["Cambridge", "Social Mobility", "Free"],
    eligibility: ["Domestic"],
    description: "Subject-specific summer schools for high-achieving students from low-income backgrounds.",
    specialFeatures: ["Experience Cambridge supervisions", "Meet current students", "Free accommodation & food"],
    noticableFacts: ["Proven to boost admission rates", "High-quality academic content"],
    applyLink: "https://undergraduate.study.cam.ac.uk",
  },
  {
    title: "ETH Zurich Summer Research Fellowship",
    university: "ETH Zurich",
    location: "Zurich, Switzerland",
    country: "Switzerland",
    level: "Undergraduate",
    category: "Research",
    fields: ["STEM"],
    format: "Offline",
    duration: "2 Months",
    tuition: 0,
    tags: ["CS", "Research", "Europe"],
    eligibility: ["International"],
    description: "Fellowship for undergraduate and graduate students in Computer Science to gain research experience at ETH Zurich.",
    specialFeatures: ["Monthly stipend", "Travel costs covered", "Social program in Switzerland"],
    noticableFacts: ["World's top CS labs", "Mountain-side campus"],
    applyLink: "https://inf.ethz.ch/studies/summer-research-fellowship",
  },
  {
    title: "EPFL Excellence Fellowships",
    university: "EPFL",
    location: "Lausanne, Switzerland",
    country: "Switzerland",
    level: "Undergraduate",
    category: "Research",
    fields: ["STEM"],
    format: "Offline",
    duration: "3 Months",
    tuition: 0,
    tags: ["Research", "Fully Funded"],
    eligibility: ["International"],
    description: "Summer internships for students from around the world to participate in research projects in Life Sciences and Engineering.",
    specialFeatures: ["Housing allowance", "Travel stipend", "Social activities"],
    noticableFacts: ["French-speaking Switzerland", "Leading engineering school"],
    applyLink: "https://sv.epfl.ch/summer-internship",
  },
  {
    title: "RISE Germany (DAAD)",
    university: "DAAD / German Unis",
    location: "Germany",
    country: "Germany",
    level: "Undergraduate",
    category: "Research",
    fields: ["STEM"],
    format: "Offline",
    duration: "3 Months",
    tuition: 0,
    tags: ["STEM", "Research", "Stipend"],
    eligibility: ["International"],
    description: "Research Internships in Science and Engineering. Matches North American and UK students with PhD mentors in Germany.",
    specialFeatures: ["Monthly stipend", "Health insurance", "Travel allowance"],
    noticableFacts: ["Learn German culture", "Professional network in Europe"],
    applyLink: "https://daad.de/rise",
  },
  {
    title: "Google STEP Internship",
    university: "Google",
    location: "Global",
    country: "Global",
    level: "Undergraduate",
    category: "Internship",
    fields: ["STEM"],
    format: "Offline",
    duration: "12 Weeks",
    tuition: 0,
    tags: ["CS", "Google", "Paid"],
    eligibility: ["International", "Domestic"],
    description: "Student Training in Engineering Program. Designed for first and second-year undergraduate students with a passion for CS.",
    specialFeatures: ["Technical training", "Project work with Googlers", "Professional development"],
    noticableFacts: ["Pipeline to regular internships", "Highly sought after"],
    applyLink: "https://buildyourfuture.withgoogle.com",
  },
  {
    title: "Microsoft Explore Program",
    university: "Microsoft",
    location: "Redmond, WA",
    country: "USA",
    level: "Undergraduate",
    category: "Internship",
    fields: ["STEM"],
    format: "Offline",
    duration: "12 Weeks",
    tuition: 0,
    tags: ["CS", "PM", "Paid"],
    eligibility: ["Domestic"],
    description: "A rotational internship program designed for first and second-year students to explore Software Engineering and Program Management.",
    specialFeatures: ["Rotational experience", "Mentorship", "Housing stipend"],
    noticableFacts: ["End-to-end product view", "Great for undecided majors"],
    applyLink: "https://careers.microsoft.com",
  },
  {
    title: "Meta University",
    university: "Meta",
    location: "Menlo Park, CA",
    country: "USA",
    level: "Undergraduate",
    category: "Internship",
    fields: ["STEM", "Business"],
    format: "Offline",
    duration: "10 Weeks",
    tuition: 0,
    tags: ["Engineering", "Analytics", "Paid"],
    eligibility: ["Domestic"],
    description: "A training-based internship program that enables students from underrepresented communities to get early career experience.",
    specialFeatures: ["Skills training", "Project work", "Mentorship"],
    noticableFacts: ["Diversity focused", "Hands-on product building"],
    applyLink: "https://metacareers.com/university",
  },
  {
    title: "Bloomberg Software Engineering",
    university: "Bloomberg LP",
    location: "NYC / London",
    country: "USA / UK",
    level: "Undergraduate",
    category: "Internship",
    fields: ["STEM"],
    format: "Offline",
    duration: "12 Weeks",
    tuition: 0,
    tags: ["Finance", "Coding", "Paid"],
    eligibility: ["International", "Domestic"],
    description: "Build the tools that drive the world's financial markets. Focus on low-latency, high-availability systems.",
    specialFeatures: ["Real-time data tech", "Professional training", "Collaborative culture"],
    noticableFacts: ["High compensation", "Strong focus on C++ and JS"],
    applyLink: "https://bloomberg.com/careers",
  },
  {
    title: "Goldman Sachs Summer Analyst",
    university: "Goldman Sachs",
    location: "Global",
    country: "Global",
    level: "Undergraduate",
    category: "Internship",
    fields: ["Business", "STEM"],
    format: "Offline",
    duration: "10 Weeks",
    tuition: 0,
    tags: ["Finance", "Banking", "Paid"],
    eligibility: ["International", "Domestic"],
    description: "A ten-week program for students to experience the day-to-day life of a financial analyst in a global firm.",
    specialFeatures: ["Client project involvement", "Networking events", "Training sessions"],
    noticableFacts: ["Elite banking entry", "High conversion to full-time"],
    applyLink: "https://goldmansachs.com/careers",
  },
  {
    title: "JPMorgan Summer Analyst",
    university: "JPMorgan Chase",
    location: "Global",
    country: "Global",
    level: "Undergraduate",
    category: "Internship",
    fields: ["Business", "STEM"],
    format: "Offline",
    duration: "10 Weeks",
    tuition: 0,
    tags: ["Finance", "Tech", "Paid"],
    eligibility: ["International", "Domestic"],
    description: "Explore career paths in Corporate & Investment Bank, Asset Management, or Commercial Banking.",
    specialFeatures: ["Intensive training", "Real deal exposure", "Leadership speakers"],
    noticableFacts: ["Largest US bank", "Global reach"],
    applyLink: "https://jpmorganchase.com/careers",
  },
  {
    title: "World Bank Internship",
    university: "World Bank Group",
    location: "Washington D.C.",
    country: "USA",
    level: "Graduate",
    category: "Internship",
    fields: ["Humanities", "Business"],
    format: "Hybrid",
    duration: "3-4 Months",
    tuition: 0,
    tags: ["Policy", "Development", "Paid"],
    eligibility: ["International"],
    description: "Opportunities for highly motivated individuals to be exposed to the mission and work of the World Bank Group.",
    specialFeatures: ["Global impact research", "Policy analysis", "International team"],
    noticableFacts: ["Requires Master's or PhD", "Focus on developing economies"],
    applyLink: "https://worldbank.org/internships",
  },
  {
    title: "United Nations Internship",
    university: "United Nations",
    location: "NY / Geneva / Vienna",
    country: "Global",
    level: "Graduate",
    category: "Internship",
    fields: ["Humanities", "Law"],
    format: "Hybrid",
    duration: "2-6 Months",
    tuition: 0,
    tags: ["Diplomacy", "International Law"],
    eligibility: ["International"],
    description: "Get a first-hand look at the day-to-day working environment of the UN and its diverse departments.",
    specialFeatures: ["Exposure to high-level meetings", "Policy drafting", "International networking"],
    noticableFacts: ["Often unpaid (some exceptions)", "Highly competitive"],
    applyLink: "https://careers.un.org",
  },
  {
    title: "WHO Internship Programme",
    university: "World Health Org",
    location: "Geneva / Regional",
    country: "Global",
    level: "Graduate",
    category: "Internship",
    fields: ["Health", "STEM"],
    format: "Hybrid",
    duration: "6-24 Weeks",
    tuition: 0,
    tags: ["Public Health", "Global Policy"],
    eligibility: ["International"],
    description: "Provides an opportunity for students to gain insight into the work of WHO and participate in international health projects.",
    specialFeatures: ["Global health monitoring", "Technical support", "Policy research"],
    noticableFacts: ["Focus on global health equity", "Diverse technical fields"],
    applyLink: "https://who.int/careers",
  },
  {
    title: "UNICEF Internship Program",
    university: "UNICEF",
    location: "Global",
    country: "Global",
    level: "Graduate",
    category: "Internship",
    fields: ["Humanities", "Health"],
    format: "Hybrid",
    duration: "6-26 Weeks",
    tuition: 0,
    tags: ["Children Rights", "Development"],
    eligibility: ["International"],
    description: "Opportunities for students to gain professional work experience in UNICEF's work for children.",
    specialFeatures: ["Field office exposure", "Data collection", "Rights advocacy"],
    noticableFacts: ["Focus on child welfare", "Global presence"],
    applyLink: "https://unicef.org/careers",
  },
  {
    title: "IMF Fund Internship",
    university: "Int. Monetary Fund",
    location: "Washington D.C.",
    country: "USA",
    level: "Graduate",
    category: "Internship",
    fields: ["Business", "Humanities"],
    format: "Offline",
    duration: "10-12 Weeks",
    tuition: 0,
    tags: ["Economics", "Finance", "Paid"],
    eligibility: ["International"],
    description: "Intensive research project for PhD students in economics or related fields.",
    specialFeatures: ["Work with senior economists", "Publication potential", "Stipend and travel"],
    noticableFacts: ["Elite economic research", "Prestigious PhD track"],
    applyLink: "https://imf.org/jobs",
  },
  {
    title: "Erasmus+ Traineeships",
    university: "European Union",
    location: "Europe",
    country: "Europe",
    level: "Undergraduate",
    category: "Internship",
    fields: ["All"],
    format: "Offline",
    duration: "2-12 Months",
    tuition: 0,
    tags: ["Exchange", "EU", "Stipend"],
    eligibility: ["International"],
    description: "Support for students to do an internship abroad in a company or any other relevant workplace in Europe.",
    specialFeatures: ["Erasmus+ grant", "Cultural exchange", "Professional recognition"],
    noticableFacts: ["Open to EU and partner countries", "Broad subject range"],
    applyLink: "https://erasmus-plus.ec.europa.eu",
  },
  {
    title: "Jackson Laboratory Summer Student Program",
    university: "The Jackson Laboratory",
    location: "Bar Harbor, ME",
    country: "USA",
    level: "Undergraduate",
    category: "Research",
    fields: ["STEM"],
    format: "Offline",
    duration: "10 Weeks",
    tuition: 0,
    tags: ["Genetics", "Bioinformatics", "Paid"],
    eligibility: ["Domestic"],
    description: "Participate in independent research under the guidance of a staff scientist. Focus on genetics, genomics, and bioinformatics.",
    specialFeatures: ["Individual research project", "Professional development", "Stipend and housing provided"],
    noticableFacts: ["Focus on mammalian genetics", "Beautiful coastal Maine campus"],
    applyLink: "https://jax.org/education-and-learning/high-school-students-and-undergraduates/summer-student-program",
  },
  {
    title: "NIH Summer Internship Program (SIP)",
    university: "National Institutes of Health",
    location: "Bethesda, MD / Global",
    country: "USA",
    level: "High School",
    category: "Internship",
    fields: ["STEM", "Medicine"],
    format: "Offline",
    duration: "8 Weeks",
    tuition: 0,
    tags: ["Biomedical", "Health", "Paid"],
    eligibility: ["Domestic"],
    description: "Provides an opportunity for students to spend a summer working at the NIH side-by-side with some of the world's leading scientists.",
    specialFeatures: ["Work in NIH laboratories", "Career development workshops", "Scientific lectures"],
    noticableFacts: ["World's largest biomedical research institution", "Multiple locations available"],
    applyLink: "https://training.nih.gov/programs/sip",
  },
  {
    title: "TASP (Telluride Association Summer Seminar)",
    university: "Telluride Association",
    location: "Various (Cornell/Maryland)",
    country: "USA",
    level: "High School",
    category: "Summer",
    fields: ["Humanities", "Social Sciences"],
    format: "Offline",
    duration: "6 Weeks",
    tuition: 0,
    tags: ["Critical Thinking", "Humanities", "Free"],
    eligibility: ["International", "Domestic"],
    description: "Free six-week educational program for high school juniors. Focuses on critical thinking and democratic community living.",
    specialFeatures: ["Full scholarship", "Seminar-style learning", "Student-run governance"],
    noticableFacts: ["One of the most prestigious humanities programs", "Intense intellectual rigor"],
    applyLink: "https://tellurideassociation.org",
  },
  {
    title: "Interlochen Arts Camp",
    university: "Interlochen Center for the Arts",
    location: "Interlochen, MI",
    country: "USA",
    level: "High School",
    category: "Summer",
    fields: ["Arts"],
    format: "Offline",
    duration: "1-6 Weeks",
    tuition: 6000,
    tags: ["Music", "Visual Arts", "Theater"],
    eligibility: ["International", "Domestic"],
    description: "A world-renowned arts program where students receive intensive training in their chosen artistic discipline.",
    specialFeatures: ["Performance opportunities", "Masterclasses with professionals", "Creative community"],
    noticableFacts: ["Alumni include many famous artists", "Beautiful wooded campus"],
    applyLink: "https://camp.interlochen.org",
  },
  {
    title: "Tanglewood Institute (BUTI)",
    university: "Boston University",
    location: "Lenox, MA",
    country: "USA",
    level: "High School",
    category: "Summer",
    fields: ["Arts"],
    format: "Offline",
    duration: "2-6 Weeks",
    tuition: 5000,
    tags: ["Classical Music", "Orchestra", "Voice"],
    eligibility: ["International", "Domestic"],
    description: "A premier summer training program for young musicians, located at the summer home of the Boston Symphony Orchestra.",
    specialFeatures: ["Work with BSO members", "Performance at Tanglewood", "Intensive musical training"],
    noticableFacts: ["World-class musical environment", "Legacy of excellence"],
    applyLink: "https://bu.edu/tanglewood",
  },
  {
    title: "Hampshire College Summer Math (HCSSiM)",
    university: "Hampshire College",
    location: "Amherst, MA",
    country: "USA",
    level: "High School",
    category: "Summer",
    fields: ["Mathematics"],
    format: "Offline",
    duration: "6 Weeks",
    tuition: 0,
    tags: ["Mathematics", "Math Camp", "Selective"],
    eligibility: ["International", "Domestic"],
    description: "An intensive six-week encounter with abstract mathematics for talented high school students.",
    specialFeatures: ["Proof-based learning", "Close interaction with faculty", "Collaborative atmosphere"],
    noticableFacts: ["Unique 'Interesting Test' application", "Focus on mathematical discovery"],
    applyLink: "https://hcssim.org",
  },
  {
    title: "Bank of America Student Leaders",
    university: "Bank of America",
    location: "Local Market / Washington DC",
    country: "USA",
    level: "High School",
    category: "Internship",
    fields: ["Business", "Leadership"],
    format: "Offline",
    duration: "8 Weeks",
    tuition: 0,
    tags: ["Leadership", "Community Service", "Paid"],
    eligibility: ["Domestic"],
    description: "Connects community-minded high school juniors and seniors to employment, skills development, and service.",
    specialFeatures: ["Paid internship at a local nonprofit", "National Student Leadership Summit", "Community leadership focus"],
    noticableFacts: ["Highly selective", "Full travel and expenses paid"],
    applyLink: "https://about.bankofamerica.com/en-us/what-guides-us/student-leaders.html",
  },
  {
    title: "NSLI-Y (National Security Language Initiative)",
    university: "U.S. Department of State",
    location: "Global",
    country: "Global",
    level: "High School",
    category: "Summer",
    fields: ["Humanities"],
    format: "Offline",
    duration: "6-8 Weeks",
    tuition: 0,
    tags: ["Language", "Cultural Exchange", "Fully Funded"],
    eligibility: ["Domestic"],
    description: "Immersive language learning programs abroad for American high school students to learn critical languages.",
    specialFeatures: ["Full scholarship", "Host family stay", "Intensive language instruction"],
    noticableFacts: ["Covers Arabic, Chinese, Hindi, Indonesian, Korean, Persian, Russian, and Turkish", "Government-sponsored"],
    applyLink: "https://nsliforyouth.org",
  },
  {
    title: "CIEE Global Navigator High School",
    university: "CIEE",
    location: "Global",
    country: "Global",
    level: "High School",
    category: "Summer",
    fields: ["Humanities", "STEM", "Arts"],
    format: "Offline",
    duration: "3-4 Weeks",
    tuition: 5000,
    tags: ["Study Abroad", "Language", "Service"],
    eligibility: ["International", "Domestic"],
    description: "Explore a new culture, learn a language, or engage in community service through study abroad programs.",
    specialFeatures: ["Multiple subject tracks", "Language immersion", "Service-learning projects"],
    noticableFacts: ["Merit and need-based scholarships available", "Over 40 destinations"],
    applyLink: "https://ciee.org/go-abroad/high-school-summer-abroad",
  },
  {
    title: "International Mathematical Olympiad (IMO)",
    university: "IMO Board",
    location: "Global",
    country: "Global",
    level: "High School",
    category: "Competition",
    fields: ["Mathematics"],
    format: "Offline",
    duration: "2 Weeks",
    tuition: 0,
    tags: ["Mathematics", "Prestige", "Global"],
    eligibility: ["International"],
    description: "The World Championship Mathematics Competition for High School students.",
    specialFeatures: ["Highest level of math competition", "Global networking", "Medal recognition"],
    noticableFacts: ["Extremely challenging problems", "Participating teams from over 100 countries"],
    applyLink: "https://imo-official.org",
  },
  {
    title: "International Olympiad in Informatics (IOI)",
    university: "IOI Board",
    location: "Global",
    country: "Global",
    level: "High School",
    category: "Competition",
    fields: ["STEM"],
    format: "Offline",
    duration: "1 Week",
    tuition: 0,
    tags: ["Coding", "Algorithms", "Prestige"],
    eligibility: ["International"],
    description: "The premier international competitive programming competition for secondary school students.",
    specialFeatures: ["Algorithmic problem solving", "Global recognition", "Tech networking"],
    noticableFacts: ["Focus on complex algorithms", "Supported by major tech companies"],
    applyLink: "https://ioinformatics.org",
  },
  {
    title: "Regeneron Science Talent Search (STS)",
    university: "Society for Science",
    location: "Washington D.C.",
    country: "USA",
    level: "High School",
    category: "Competition",
    fields: ["STEM"],
    format: "Hybrid",
    duration: "Year-long",
    tuition: 0,
    tags: ["Research", "STEM", "Awards"],
    eligibility: ["Domestic"],
    description: "The nation's oldest and most prestigious science and math competition for high school seniors.",
    specialFeatures: ["Substantial cash awards", "Interaction with top scientists", "Prestige in college admissions"],
    noticableFacts: ["Alumni include Nobel Prize winners", "Focus on original research"],
    applyLink: "https://societyforscience.org/regeneron-sts",
  },
  {
    title: "Google Code-in (Legacy)",
    university: "Google Open Source",
    location: "Online",
    country: "Global",
    level: "High School",
    category: "Competition",
    fields: ["STEM"],
    format: "Online",
    duration: "7 Weeks",
    tuition: 0,
    tags: ["Open Source", "Coding", "Rewards"],
    eligibility: ["International", "Domestic"],
    description: "A contest to introduce pre-university students to open source software development.",
    specialFeatures: ["Small task-based contributions", "Mentorship from OSS projects", "Google prizes"],
    noticableFacts: ["Accessible entry into open source", "Global community"],
    applyLink: "https://codein.withgoogle.com",
  },
  {
    title: "Blue Stamp Engineering",
    university: "BSE Global",
    location: "Online / NY / CA",
    country: "USA",
    level: "High School",
    category: "Summer",
    fields: ["STEM"],
    format: "Hybrid",
    duration: "6 Weeks",
    tuition: 4500,
    tags: ["Engineering", "Hardware", "Robotics"],
    eligibility: ["International", "Domestic"],
    description: "A hands-on engineering program where students build a project of their own choosing from scratch.",
    specialFeatures: ["Individual engineering project", "Technical skill building", "Career mentorship"],
    noticableFacts: ["Focus on physical builds", "Great for portfolios"],
    applyLink: "https://bluestampengineering.com",
  },
  {
    title: "Polygence Research Program",
    university: "Polygence",
    location: "Online / Global",
    country: "USA",
    level: "High School",
    category: "Research",
    fields: ["All"],
    format: "Online",
    duration: "10-20 Weeks",
    tuition: 2500,
    tags: ["Mentorship", "Research", "Independent"],
    eligibility: ["International", "Domestic"],
    description: "Matches high school students with expert mentors to conduct personalized research projects.",
    specialFeatures: ["1-on-1 mentorship", "Personalized project scope", "Publication support"],
    noticableFacts: ["Broad subject range", "Flexible scheduling"],
    applyLink: "https://polygence.org",
  },
  {
    title: "Indigo Research",
    university: "Indigo Research",
    location: "Online / Global",
    country: "USA",
    level: "High School",
    category: "Research",
    fields: ["STEM", "Humanities", "Business"],
    format: "Online",
    duration: "12 Weeks",
    tuition: 3500,
    tags: ["Mentorship", "Publication", "Ivy League"],
    eligibility: ["International", "Domestic"],
    description: "Connects students with mentors from world-class universities to conduct high-level research.",
    specialFeatures: ["Academic publication guidance", "Network with researchers", "Certificate of completion"],
    noticableFacts: ["Mentors from top global universities", "Rigorous academic standard"],
    applyLink: "https://indigoresearch.org",
  },
  {
    title: "Smithsonian Internships",
    university: "Smithsonian Institution",
    location: "Washington D.C. / Global",
    country: "USA",
    level: "Undergraduate",
    category: "Internship",
    fields: ["Humanities", "Arts", "STEM"],
    format: "Hybrid",
    duration: "10 Weeks",
    tuition: 0,
    tags: ["Museums", "History", "Research"],
    eligibility: ["International", "Domestic"],
    description: "Internships at the world's largest museum, education, and research complex.",
    specialFeatures: ["Curatorial research", "Museum management", "Archive work"],
    noticableFacts: ["Diverse subject areas", "Historic institutions"],
    applyLink: "https://smithsonianofi.com",
  },
  {
    title: "Walt Disney World Internship",
    university: "Disney",
    location: "Orlando, FL",
    country: "USA",
    level: "Undergraduate",
    category: "Internship",
    fields: ["Business", "Arts", "STEM"],
    format: "Offline",
    duration: "4-6 Months",
    tuition: 0,
    tags: ["Hospitality", "Entertainment", "Paid"],
    eligibility: ["International", "Domestic"],
    description: "Gain hands-on experience at Disney Parks & Resorts in roles ranging from park operations to engineering.",
    specialFeatures: ["Disney College Program", "Professional development", "Park access"],
    noticableFacts: ["Global hospitality standard", "High networking value"],
    applyLink: "https://jobs.disneycareers.com",
  },
  {
    title: "United Nations Volunteers",
    university: "United Nations",
    location: "Global",
    country: "Global",
    level: "Graduate",
    category: "Internship",
    fields: ["Humanities", "Health"],
    format: "Offline",
    duration: "6-12 Months",
    tuition: 0,
    tags: ["Development", "Peace", "Volunteer"],
    eligibility: ["International"],
    description: "Contribute to peace and development through volunteerism worldwide with the UN.",
    specialFeatures: ["Living allowance provided", "Global field assignments", "Direct development impact"],
    noticableFacts: ["Requires 2+ years of experience", "Life-changing global work"],
    applyLink: "https://unv.org",
  },
  {
    title: "Schwarzman Scholars Summer",
    university: "Tsinghua University",
    location: "Beijing, China",
    country: "China",
    level: "Graduate",
    category: "Summer",
    fields: ["Business", "Humanities", "Leadership"],
    format: "Offline",
    duration: "4 Weeks",
    tuition: 0,
    tags: ["Leadership", "China", "Global Affairs"],
    eligibility: ["International"],
    description: "Intensive summer leadership program for future global leaders to understand China's role in the world.",
    specialFeatures: ["Elite networking", "High-level policy briefings", "Cultural immersion"],
    noticableFacts: ["Fully funded", "Highly competitive"],
    applyLink: "https://schwarzmanscholars.org",
  },
  {
    title: "Princeton Bridge Year",
    university: "Princeton University",
    location: "Global (Various)",
    country: "Global",
    level: "High School",
    category: "University",
    fields: ["Humanities", "Interdisciplinary"],
    format: "Offline",
    duration: "9 Months",
    tuition: 0,
    tags: ["Gap Year", "Service", "Immersive"],
    eligibility: ["Domestic"],
    description: "A tuition-free program that allows incoming freshmen to spend a year engaged in community service abroad.",
    specialFeatures: ["Full scholarship", "Community service immersion", "Language learning"],
    noticableFacts: ["Alternative to starting college immediately", "Deep cultural engagement"],
    applyLink: "https://bridgeyear.princeton.edu",
  },
  {
    title: "Stanford Summer Session",
    university: "Stanford University",
    location: "Stanford, CA",
    country: "USA",
    level: "High School",
    category: "Summer",
    fields: ["All"],
    format: "Hybrid",
    duration: "8 Weeks",
    tuition: 15000,
    tags: ["Stanford", "College Credit"],
    eligibility: ["International", "Domestic"],
    description: "Join the Stanford community for a summer of high-intensity learning and research.",
    specialFeatures: ["Take real Stanford courses", "Earn university credit", "Campus activities"],
    noticableFacts: ["Rigorous academic standards", "Global student cohort"],
    applyLink: "https://summer.stanford.edu",
  },
  {
    title: "Columbia Summer Immersion",
    university: "Columbia University",
    location: "NYC / Online",
    country: "USA",
    level: "High School",
    category: "Summer",
    fields: ["STEM", "Humanities", "Arts"],
    format: "Hybrid",
    duration: "3 Weeks",
    tuition: 6000,
    tags: ["NYC", "Ivy League", "Immersion"],
    eligibility: ["International", "Domestic"],
    description: "Experience university life in New York City while exploring academic interests in depth.",
    specialFeatures: ["NYC-based learning", "Faculty-led seminars", "College preparation"],
    noticableFacts: ["Intense subject focus", "Ivy League environment"],
    applyLink: "https://precollege.sps.columbia.edu",
  },
  {
    title: "Brown Pre-College Programs",
    university: "Brown University",
    location: "Providence, RI",
    country: "USA",
    level: "High School",
    category: "Summer",
    fields: ["STEM", "Humanities", "Arts"],
    format: "Hybrid",
    duration: "1-4 Weeks",
    tuition: 4500,
    tags: ["Brown", "Academic Discovery"],
    eligibility: ["International", "Domestic"],
    description: "Courses designed to prepare students for the rigors of university learning and explore new subjects.",
    specialFeatures: ["No-grades learning", "Diverse course catalog", "Residential experience"],
    noticableFacts: ["Focus on 'The Joy of Learning'", "Over 300 courses"],
    applyLink: "https://precollege.brown.edu",
  },
  {
    title: "Georgetown Summer Medical",
    university: "Georgetown University",
    location: "Washington D.C.",
    country: "USA",
    level: "High School",
    category: "Summer",
    fields: ["Medicine"],
    format: "Offline",
    duration: "1 Week",
    tuition: 3000,
    tags: ["Medicine", "Anatomy", "Clinical"],
    eligibility: ["International", "Domestic"],
    description: "A fast-paced immersion into the world of medicine and clinical practice at a top medical center.",
    specialFeatures: ["Anatomy lab tours", "Clinical simulations", "Medical ethics seminars"],
    noticableFacts: ["Hands-on exposure", "Located in the nation's capital"],
    applyLink: "https://summer.georgetown.edu",
  },
  {
    title: "Johns Hopkins CTY Summer",
    university: "Johns Hopkins CTY",
    location: "Various / Online",
    country: "USA",
    level: "High School",
    category: "Summer",
    fields: ["STEM", "Humanities"],
    format: "Hybrid",
    duration: "3 Weeks",
    tuition: 5000,
    tags: ["Gifted", "Advanced", "CTY"],
    eligibility: ["International", "Domestic"],
    description: "Rigorous academic programs for advanced learners across various campus locations.",
    specialFeatures: ["Talent search based entry", "Highly advanced curriculum", "Strong peer network"],
    noticableFacts: ["Gold standard for gifted education", "Long-standing history"],
    applyLink: "https://cty.jhu.edu",
  },
  {
    title: "Duke Summer Session",
    university: "Duke University",
    location: "Durham, NC",
    country: "USA",
    level: "High School",
    category: "Summer",
    fields: ["STEM", "Humanities"],
    format: "Offline",
    duration: "4 Weeks",
    tuition: 8000,
    tags: ["Duke", "Research", "College Prep"],
    eligibility: ["International", "Domestic"],
    description: "Live and learn at Duke University, participating in credit-bearing or enrichment courses.",
    specialFeatures: ["Duke faculty interaction", "Campus living", "Academic rigor"],
    noticableFacts: ["Top-tier university experience", "Comprehensive social programming"],
    applyLink: "https://summersession.duke.edu",
  },
  {
    title: "UChicago Summer Session",
    university: "University of Chicago",
    location: "Chicago, IL",
    country: "USA",
    level: "High School",
    category: "Summer",
    fields: ["Humanities", "STEM", "Social Sciences"],
    format: "Hybrid",
    duration: "3-5 Weeks",
    tuition: 7000,
    tags: ["Critical Inquiry", "Intense"],
    eligibility: ["International", "Domestic"],
    description: "Experience the unique intellectual culture of UChicago through intensive seminars and courses.",
    specialFeatures: ["Inquiry-based learning", "Faculty-led research tracks", "Urban campus life"],
    noticableFacts: ["Focus on 'The Life of the Mind'", "Academic intensity"],
    applyLink: "https://summer.uchicago.edu",
  },
  {
    title: "Northwestern NHSI (Cherubs)",
    university: "Northwestern University",
    location: "Evanston, IL",
    country: "USA",
    level: "High School",
    category: "Summer",
    fields: ["Arts", "Humanities"],
    format: "Offline",
    duration: "5 Weeks",
    tuition: 6000,
    tags: ["Theatre", "Film", "Debate"],
    eligibility: ["International", "Domestic"],
    description: "The National High School Institute, affectionately known as 'Cherubs', offers intensive programs in arts and communication.",
    specialFeatures: ["Professional-level training", "Collaborative projects", "Network with industry pros"],
    noticableFacts: ["Elite theatre program", "Legacy of famous alumni"],
    applyLink: "https://nhsi.northwestern.edu",
  },
  {
    title: "LSE Summer School",
    university: "London School of Economics",
    location: "London, UK",
    country: "UK",
    level: "Undergraduate",
    category: "Summer",
    fields: ["Business", "Humanities", "Social Sciences"],
    format: "Offline",
    duration: "3 Weeks",
    tuition: 4000,
    tags: ["Economics", "Finance", "London"],
    eligibility: ["International"],
    description: "The largest summer school of its kind in Europe, offering over 100 courses across various social science disciplines.",
    specialFeatures: ["LSE faculty lectures", "Global networking", "London city experience"],
    noticableFacts: ["World's leading social science hub", "High-intensity learning"],
    applyLink: "https://lse.ac.uk/summer-school",
  },
  {
    title: "Sciences Po Summer School",
    university: "Sciences Po",
    location: "Paris, France",
    country: "France",
    level: "Undergraduate",
    category: "Summer",
    fields: ["Humanities", "Social Sciences"],
    format: "Offline",
    duration: "4 Weeks",
    tuition: 3500,
    tags: ["International Relations", "Paris"],
    eligibility: ["International"],
    description: "An intensive program in social sciences and French language, held in the heart of Paris.",
    specialFeatures: ["Politics & IR focus", "French language tracks", "Central Paris campus"],
    noticableFacts: ["Elite French institution", "Prestigious political science network"],
    applyLink: "https://sciencespo.fr/summer-school",
  },
  {
    title: "HEC Paris Summer School",
    university: "HEC Paris",
    location: "Jouy-en-Josas, France",
    country: "France",
    level: "Undergraduate",
    category: "Summer",
    fields: ["Business"],
    format: "Offline",
    duration: "2 Weeks",
    tuition: 3000,
    tags: ["Business", "Entrepreneurship", "Elite"],
    eligibility: ["International"],
    description: "Intensive business programs focused on innovation, entrepreneurship, and luxury management.",
    specialFeatures: ["Top-tier business faculty", "Project-based learning", "Campus residency"],
    noticableFacts: ["Ranked #1 Business School in Europe", "Global business network"],
    applyLink: "https://hec.edu/summer-school",
  },
  {
    title: "Bocconi Summer School",
    university: "Bocconi University",
    location: "Milan, Italy",
    country: "Italy",
    level: "Undergraduate",
    category: "Summer",
    fields: ["Business", "Humanities"],
    format: "Offline",
    duration: "3 Weeks",
    tuition: 2800,
    tags: ["Finance", "Management", "Milan"],
    eligibility: ["International"],
    description: "Explore the intersection of business, law, and economics in the vibrant city of Milan.",
    specialFeatures: ["Case study method", "Company visits", "Social program in Italy"],
    noticableFacts: ["Leading European business school", "Strong focus on international markets"],
    applyLink: "https://unibocconi.eu/summerschool",
  },
  {
    title: "Tsinghua Global Summer School",
    university: "Tsinghua University",
    location: "Beijing, China",
    country: "China",
    level: "Undergraduate",
    category: "Summer",
    fields: ["STEM", "Business", "Humanities"],
    format: "Hybrid",
    duration: "2 Weeks",
    tuition: 0,
    tags: ["China", "Innovation", "Global"],
    eligibility: ["International"],
    description: "Focus on innovation, sustainable development, and global leadership in a Chinese context.",
    specialFeatures: ["Tsinghua faculty lectures", "Cultural workshops", "Cross-disciplinary collaboration"],
    noticableFacts: ["Top-ranked university in Asia", "Fully funded for many participants"],
    applyLink: "https://tsinghua.edu.cn",
  },
  {
    title: "University of Tokyo GSP",
    university: "University of Tokyo",
    location: "Tokyo, Japan",
    country: "Japan",
    level: "Undergraduate",
    category: "Summer",
    fields: ["STEM", "Humanities"],
    format: "Offline",
    duration: "2 Weeks",
    tuition: 1500,
    tags: ["Japan", "Science", "Cultural"],
    eligibility: ["International"],
    description: "Global Summer Program offering courses in Japanese culture, society, and cutting-edge science.",
    specialFeatures: ["Field trips in Japan", "Laboratory visits", "Interaction with UTokyo students"],
    noticableFacts: ["Prestigious 'Todai' experience", "Japan's leading university"],
    applyLink: "https://u-tokyo.ac.jp",
  },
  {
    title: "SNU Summer Program",
    university: "Seoul National University",
    location: "Seoul, South Korea",
    country: "South Korea",
    level: "Undergraduate",
    category: "Summer",
    fields: ["Humanities", "STEM", "Business"],
    format: "Offline",
    duration: "5 Weeks",
    tuition: 2500,
    tags: ["Korea", "Culture", "Global"],
    eligibility: ["International"],
    description: "Comprehensive summer program exploring Korean language, history, and modern technology.",
    specialFeatures: ["Seoul city tours", "K-Pop and K-Drama workshops", "Academic exchange"],
    noticableFacts: ["South Korea's top university", "Modern high-tech campus"],
    applyLink: "https://snu.ac.kr",
  },
  {
    title: "NTU Summer Program",
    university: "Nanyang Technological Univ",
    location: "Singapore",
    country: "Singapore",
    level: "Undergraduate",
    category: "Summer",
    fields: ["STEM", "Business"],
    format: "Offline",
    duration: "4 Weeks",
    tuition: 3000,
    tags: ["Singapore", "Technology", "Innovation"],
    eligibility: ["International"],
    description: "Focus on innovation and entrepreneurship in the heart of Asia's tech hub.",
    specialFeatures: ["Incubator visits", "Project pitch competition", "Sustainable campus life"],
    noticableFacts: ["World's most beautiful campus", "Top engineering focus"],
    applyLink: "https://ntu.edu.sg",
  },
  {
    title: "NUS Enterprise Summer",
    university: "National Univ of Singapore",
    location: "Singapore",
    country: "Singapore",
    level: "Undergraduate",
    category: "Summer",
    fields: ["Business"],
    format: "Offline",
    duration: "2 Weeks",
    tuition: 3500,
    tags: ["Entrepreneurship", "Venture Capital"],
    eligibility: ["International"],
    description: "Deep dive into the Singapore startup ecosystem and venture capital landscape.",
    specialFeatures: ["Company founder talks", "Venture pitching", "Networking with investors"],
    noticableFacts: ["Gateway to Asian markets", "Intensive startup focus"],
    applyLink: "https://enterprise.nus.edu.sg",
  },
  {
    title: "Sydney Summer School",
    university: "University of Sydney",
    location: "Sydney, Australia",
    country: "Australia",
    level: "Undergraduate",
    category: "Summer",
    fields: ["STEM", "Humanities", "Arts"],
    format: "Offline",
    duration: "6 Weeks",
    tuition: 4000,
    tags: ["Australia", "Beach Life", "Academic"],
    eligibility: ["International"],
    description: "Study during the Australian summer (Jan-Feb) and explore the unique culture of Sydney.",
    specialFeatures: ["Coastal field trips", "Australian history courses", "Global student mix"],
    noticableFacts: ["Southern Hemisphere schedule", "Beautiful historic campus"],
    applyLink: "https://sydney.edu.au",
  },
  {
    title: "Melbourne Summer Term",
    university: "University of Melbourne",
    location: "Melbourne, Australia",
    country: "Australia",
    level: "Undergraduate",
    category: "Summer",
    fields: ["STEM", "Humanities"],
    format: "Offline",
    duration: "4 Weeks",
    tuition: 3800,
    tags: ["Melbourne", "Urban Life", "Research"],
    eligibility: ["International"],
    description: "Intensive summer subjects in the cultural capital of Australia.",
    specialFeatures: ["Urban exploration", "Research-led teaching", "Vibrant student life"],
    noticableFacts: ["Australia's top-ranked university", "Dynamic city campus"],
    applyLink: "https://unimelb.edu.au",
  },
  {
    title: "Oxford Executive Education",
    university: "Oxford Saïd Business School",
    location: "Oxford, UK",
    country: "UK",
    level: "Graduate",
    category: "University",
    fields: ["Business", "Leadership"],
    format: "Hybrid",
    duration: "1-2 Weeks",
    tuition: 10000,
    tags: ["Executive", "Networking", "Oxford"],
    eligibility: ["International"],
    description: "Short, high-impact leadership and business programs for experienced professionals.",
    specialFeatures: ["Oxford faculty coaching", "Elite professional network", "Historic college stay"],
    noticableFacts: ["Global executive prestige", "High-level strategic focus"],
    applyLink: "https://sbs.ox.ac.uk",
  },
  {
    title: "INSEAD Summer Program",
    university: "INSEAD",
    location: "Fontainebleau, France",
    country: "France",
    level: "Graduate",
    category: "Summer",
    fields: ["Business"],
    format: "Offline",
    duration: "2 Weeks",
    tuition: 8000,
    tags: ["Business", "International", "MBA"],
    eligibility: ["International"],
    description: "Mini-MBA experience focused on global business management and international strategy.",
    specialFeatures: ["Case study marathons", "Global team projects", "Forest campus experience"],
    noticableFacts: ["The Business School for the World", "Highly diverse cohort"],
    applyLink: "https://insead.edu",
  },
  {
    title: "London Business School Summer",
    university: "London Business School",
    location: "London, UK",
    country: "UK",
    level: "Graduate",
    category: "Summer",
    fields: ["Business"],
    format: "Offline",
    duration: "3 Weeks",
    tuition: 9000,
    tags: ["Finance", "London", "Elite"],
    eligibility: ["International"],
    description: "Advanced finance and management programs in the world's financial heart.",
    specialFeatures: ["City of London visits", "Professional mentorship", "Strategic networking"],
    noticableFacts: ["Top-tier global rankings", "Premier finance focus"],
    applyLink: "https://london.edu",
  },
  {
    title: "MIT Bootcamps",
    university: "MIT",
    location: "Online / Global",
    country: "USA",
    level: "Undergraduate",
    category: "Summer",
    fields: ["Business", "STEM"],
    format: "Hybrid",
    duration: "1 Week",
    tuition: 5000,
    tags: ["Entrepreneurship", "Innovation", "MIT"],
    eligibility: ["International", "Domestic"],
    description: "Intensive, week-long programs where participants start a venture and learn the MIT way of innovating.",
    specialFeatures: ["Extreme entrepreneurship", "Pitching to MIT faculty", "Alumni community access"],
    noticableFacts: ["High intensity 'drinking from a firehose'", "Global locations"],
    applyLink: "https://bootcamp.mit.edu",
  },
  {
    title: "Singularity University Summer",
    university: "Singularity University",
    location: "Online / Silicon Valley",
    country: "USA",
    level: "Graduate",
    category: "Summer",
    fields: ["STEM", "Business"],
    format: "Hybrid",
    duration: "2-4 Weeks",
    tuition: 12000,
    tags: ["Exponential Tech", "Future"],
    eligibility: ["International"],
    description: "Explore exponential technologies and how to use them to solve humanity's greatest challenges.",
    specialFeatures: ["Silicon Valley network", "Future-focused curriculum", "Impact project focus"],
    noticableFacts: ["Founded by Ray Kurzweil & Peter Diamandis", "High-tech futurist focus"],
    applyLink: "https://su.org",
  },
  {
    title: "Aalto University Summer School",
    university: "Aalto University",
    location: "Espoo, Finland",
    country: "Finland",
    level: "Undergraduate",
    category: "Summer",
    fields: ["STEM", "Arts", "Business"],
    format: "Offline",
    duration: "2-3 Weeks",
    tuition: 2000,
    tags: ["Design", "Innovation", "Nordic"],
    eligibility: ["International"],
    description: "Nordic focus on design thinking, technology, and entrepreneurship.",
    specialFeatures: ["Design Factory access", "Nordic nature trips", "Collaborative design projects"],
    noticableFacts: ["World leader in design education", "Unique interdisciplinary focus"],
    applyLink: "https://aalto.fi/summer-school",
  },
  {
    title: "TU Delft Summer School",
    university: "TU Delft",
    location: "Delft, Netherlands",
    country: "Netherlands",
    level: "Undergraduate",
    category: "Summer",
    fields: ["STEM"],
    format: "Offline",
    duration: "2 Weeks",
    tuition: 2200,
    tags: ["Water Management", "Engineering"],
    eligibility: ["International"],
    description: "Leading programs in water management, sustainable energy, and aerospace engineering.",
    specialFeatures: ["Dike and dam visits", "Advanced lab access", "Bicycle-friendly campus"],
    noticableFacts: ["World's best in water engineering", "Historic technical university"],
    applyLink: "https://tudelft.nl",
  },
  {
    title: "KTH Summer School",
    university: "KTH Royal Institute",
    location: "Stockholm, Sweden",
    country: "Sweden",
    level: "Undergraduate",
    category: "Summer",
    fields: ["STEM"],
    format: "Offline",
    duration: "4 Weeks",
    tuition: 2500,
    tags: ["Sustainability", "Tech", "Sweden"],
    eligibility: ["International"],
    description: "Sustainability and smart city technology in one of Europe's most innovative cities.",
    specialFeatures: ["Smart city tours", "Innovation hub visits", "Stockholm archipelago trips"],
    noticableFacts: ["Leading technical school in Sweden", "Strong sustainability focus"],
    applyLink: "https://kth.se",
  },
  {
    title: "University of Helsinki Summer",
    university: "University of Helsinki",
    location: "Helsinki, Finland",
    country: "Finland",
    level: "Graduate",
    category: "Summer",
    fields: ["Humanities", "Social Sciences"],
    format: "Offline",
    duration: "3 Weeks",
    tuition: 1800,
    tags: ["Education", "Policy", "Nordic"],
    eligibility: ["International"],
    description: "Deep dive into the Finnish education system and welfare state models.",
    specialFeatures: ["School visits", "Policy debates", "Sauna and nature experiences"],
    noticableFacts: ["World's best education system focus", "Top-tier Nordic research"],
    applyLink: "https://helsinki.fi/summer-school",
  },
  {
    title: "Copenhagen Summer University",
    university: "University of Copenhagen",
    location: "Copenhagen, Denmark",
    country: "Denmark",
    level: "Undergraduate",
    category: "Summer",
    fields: ["STEM", "Health", "Humanities"],
    format: "Offline",
    duration: "2 Weeks",
    tuition: 2000,
    tags: ["Health", "Sustainability", "Denmark"],
    eligibility: ["International"],
    description: "Focus on global health, sustainability, and the Danish 'Hygge' lifestyle.",
    specialFeatures: ["Global health projects", "Sustainability walks", "Danish culture workshops"],
    noticableFacts: ["Oldest university in Denmark", "Leading health research"],
    applyLink: "https://summer.ku.dk",
  },
];

async function main() {
  console.log("Seeding programs data...\n");

  // Clear existing programs
  await prisma.contentProgram.deleteMany();
  console.log("Cleared existing programs.");

  for (const p of programsData) {
    const { level, format, ...rest } = p;
    await prisma.contentProgram.create({ 
      data: {
        ...rest,
        degreeLevel: level,
        studyMode: format
      } 
    });
  }

  const count = await prisma.contentProgram.count();
  console.log(`✓ Created ${count} programs.`);
  console.log("\n✅ Program seed complete!");
}

main()
  .catch(console.error)
  .finally(async () => {
    await prisma.$disconnect();
    await pool.end();
  });
