"use client";
import { useState, useMemo } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { PublicHeader } from "@/components/PublicHeader";
import { InfoModal } from "@/components/InfoModal";
import styles from "./page.module.css";
import { Search, MapPin, GraduationCap, Sparkles, Bookmark, Filter as FilterIcon, ChevronDown, FlaskConical, Globe, Briefcase, Palette, Heart, BookOpen, Laptop, Trophy, Coins, UserCheck, Monitor } from "lucide-react";
import { useSaved } from "@/context/SavedContext";

type Program = {
  id: string; title: string; university: string; location: string; country: string;
  logo?: string; image?: string; 
  level: "High School" | "Undergraduate" | "Graduate";
  category: "Summer" | "Research" | "Internship" | "Competition" | "University";
  fields: string[]; 
  format: "Online" | "Offline" | "Hybrid"; 
  duration: string; tuition: number; tags: string[];
  eligibility: ("International" | "Domestic")[];
  description?: string; special_features?: string[]; noticable_facts?: string[];
  apply_link?: string; featured?: boolean;
};

const programsData: Program[] = [
  {
    id: "p1",
    title: "SSP (Summer Science Program)",
    university: "SSP International",
    location: "Various (US)",
    country: "USA",
    level: "High School",
    category: "Research",
    fields: ["STEM", "Mathematics"],
    format: "Offline",
    duration: "6 Weeks",
    tuition: 0,
    tags: ["Astrophysics", "Biochemistry", "Genomics"],
    eligibility: ["International", "Domestic"],
    description: "A legacy program focusing on collaborative research in Astrophysics, Biochemistry, or Genomics. Students work in teams of three to complete a real-world research project.",
    special_features: ["Collaborative team research", "PhD faculty mentorship", "Legacy alumni network"],
    noticable_facts: ["One of the oldest summer programs", "Hands-on data collection", "High selectivity"],
    apply_link: "https://summerscience.org",
    featured: true
  },
  {
    id: "p2",
    title: "Lumiere Research Scholar Program",
    university: "Lumiere Education",
    location: "Online / Global",
    country: "USA",
    level: "High School",
    category: "Research",
    fields: ["STEM", "Humanities", "Interdisciplinary"],
    format: "Online",
    duration: "12 Weeks",
    tuition: 3950,
    tags: ["Mentorship", "Research Paper", "PhD"],
    eligibility: ["International", "Domestic"],
    description: "Provides 1-on-1 mentorship with PhD researchers from top-tier universities. It is highly flexible and focuses on producing a high-quality, independent research paper.",
    special_features: ["1-on-1 PhD mentorship", "Individual research paper", "Flexible start dates"],
    noticable_facts: ["Produces publishable quality work", "Mentors from Ivy League schools"],
    apply_link: "https://lumiere-education.com",
  },
  {
    id: "p3",
    title: "Pioneer Academics",
    university: "Pioneer Academics",
    location: "Online / Global",
    country: "USA",
    level: "High School",
    category: "Research",
    fields: ["STEM", "Humanities", "Business"],
    format: "Online",
    duration: "10 Weeks",
    tuition: 6000,
    tags: ["Credit", "Oberlin", "Research"],
    eligibility: ["International", "Domestic"],
    description: "A global online research institute known for its high standards and partnership with Oberlin College to offer academic credit.",
    special_features: ["Oberlin College credit", "Standardized research process", "Diverse subject areas"],
    noticable_facts: ["First online research program for HS", "Strict evaluation metrics"],
    apply_link: "https://pioneeracademics.com",
  },
  {
    id: "p4",
    title: "PROMYS / ROSS / HCSSiM",
    university: "Boston Univ / Ohio State",
    location: "MA & OH",
    country: "USA",
    level: "High School",
    category: "Summer",
    fields: ["Mathematics"],
    format: "Offline",
    duration: "6 Weeks",
    tuition: 0,
    tags: ["Number Theory", "Math Camp", "Selective"],
    eligibility: ["International", "Domestic"],
    description: "The 'Holy Trinity' of math camps focusing on deep number theory and mathematical logic. They look for 'mathematical maturity.'",
    special_features: ["Proof-based learning", "Legendary problem sets", "Immersion in math culture"],
    noticable_facts: ["Low acceptance rates", "Highly regarded by top colleges"],
    apply_link: "https://promys.org",
  },
  {
    id: "p5",
    title: "Honors Summer Math Camp (HSMC)",
    university: "Texas State University",
    location: "San Marcos, TX",
    country: "USA",
    level: "High School",
    category: "Research",
    fields: ["Mathematics", "STEM"],
    format: "Offline",
    duration: "6 Weeks",
    tuition: 0,
    tags: ["Research", "Math", "Residential"],
    eligibility: ["International", "Domestic"],
    description: "A residential program that emphasizes developing creative and critical thinking through math research projects.",
    special_features: ["Team research projects", "Creative problem solving", "Social activities"],
    noticable_facts: ["Focus on 'mathematical thinking'", "Long-standing tradition"],
    apply_link: "https://txstate.edu/hsmc",
  },
  {
    id: "p6",
    title: "TechGirls",
    university: "U.S. Dept of State",
    location: "Washington D.C. + Hybrid",
    country: "USA",
    level: "High School",
    category: "Summer",
    fields: ["STEM", "Interdisciplinary"],
    format: "Hybrid",
    duration: "4 Weeks",
    tuition: 0,
    tags: ["Leadership", "Girls in STEM", "Exchange"],
    eligibility: ["International"],
    description: "An exchange program for young women in STEM focusing on tech-leadership and community action projects.",
    special_features: ["Fully funded exchange", "Industry job shadowing", "Follow-on project support"],
    noticable_facts: ["Covers all travel & board", "Focus on underrepresented regions"],
    apply_link: "https://techgirlsglobal.org",
  },
  {
    id: "p7",
    title: "Bentley Wall Street 101",
    university: "Bentley University",
    location: "Waltham, MA",
    country: "USA",
    level: "High School",
    category: "Summer",
    fields: ["Business"],
    format: "Offline",
    duration: "1 Week",
    tuition: 1500,
    tags: ["Finance", "Bloomberg", "Trading"],
    eligibility: ["International", "Domestic"],
    description: "An intensive introduction to global finance, stock markets, and investment research using Bloomberg terminals.",
    special_features: ["Bloomberg Terminal access", "Stock pitch competition", "Trading simulations"],
    noticable_facts: ["Professional-grade tools", "Short, high-intensity learning"],
    apply_link: "https://bentley.edu/wallstreet101",
  },
  {
    id: "p8",
    title: "LaunchX",
    university: "LaunchX Global",
    location: "Various / Online",
    country: "USA",
    level: "High School",
    category: "Summer",
    fields: ["Business", "Interdisciplinary"],
    format: "Hybrid",
    duration: "4 Weeks",
    tuition: 0,
    tags: ["Entrepreneurship", "Startups", "Founder"],
    eligibility: ["International", "Domestic"],
    description: "Rigorous entrepreneurship program where students actually start a company during the summer. Available both in-person and online.",
    special_features: ["Start a real company", "Pitch to investors", "Founding team formation"],
    noticable_facts: ["Focus on action over theory", "Strong startup alumni"],
    apply_link: "https://launchx.com",
  },
  {
    id: "p9",
    title: "Wharton Global Youth Program",
    university: "UPenn Wharton",
    location: "Philadelphia, PA",
    country: "USA",
    level: "High School",
    category: "Summer",
    fields: ["Business", "STEM"],
    format: "Offline",
    duration: "2-4 Weeks",
    tuition: 5000,
    tags: ["Wharton", "Business", "Leadership"],
    eligibility: ["International", "Domestic"],
    description: "Various tracks like 'Leadership in the Business World' and 'Data Science' hosted at the University of Pennsylvania.",
    special_features: ["Ivy League experience", "Wharton faculty lectures", "Business simulations"],
    noticable_facts: ["Top-tier business networking", "Multiple subject tracks"],
    apply_link: "https://globalyouth.wharton.upenn.edu",
  },
  {
    id: "p10",
    title: "UWC Short Courses",
    university: "United World Colleges",
    location: "Global",
    country: "Global",
    level: "High School",
    category: "Summer",
    fields: ["Humanities", "Interdisciplinary"],
    format: "Offline",
    duration: "2 Weeks",
    tuition: 1200,
    tags: ["Sustainability", "Peacebuilding", "Culture"],
    eligibility: ["International", "Domestic"],
    description: "Shorter versions of the UWC experience, focusing on sustainability, peacebuilding, and intercultural understanding.",
    special_features: ["Intercultural dialogue", "Experiential learning", "Peacebuilding workshops"],
    noticable_facts: ["Hosted at UWC campuses globally", "Financial aid often available"],
    apply_link: "https://uwc.org/short-courses",
  },
  {
    id: "p11",
    title: "Yale Young Global Scholars",
    university: "Yale University",
    location: "New Haven, CT",
    country: "USA",
    level: "High School",
    category: "Summer",
    fields: ["STEM", "Humanities", "Business"],
    format: "Offline",
    duration: "2 Weeks",
    tuition: 6500,
    tags: ["Yale", "Leadership", "Global"],
    eligibility: ["International", "Domestic"],
    description: "A world-renowned academic leadership program. Offers tracks ranging from Science & Technology to Politics, Law & Economics.",
    special_features: ["Yale faculty seminars", "Capstone projects", "Global peer community"],
    noticable_facts: ["One of the most diverse programs", "Yale campus residency"],
    apply_link: "https://globalscholars.yale.edu",
  },
  {
    id: "p12",
    title: "MIT PRIMES (Research in Math)",
    university: "MIT",
    location: "Cambridge, MA",
    country: "USA",
    level: "High School",
    category: "Research",
    fields: ["STEM", "Mathematics"],
    format: "Hybrid",
    duration: "1 Year",
    tuition: 0,
    tags: ["Mathematics", "Research", "Competition"],
    eligibility: ["International", "Domestic"],
    description: "Program for Research in Mathematics, Engineering, and Science for High School Students. Includes individual and group research projects.",
    special_features: ["Mentorship by MIT graduate students", "Advanced math research", "Publication opportunities"],
    noticable_facts: ["Tuition-free", "Highly selective academic track"],
    apply_link: "https://math.mit.edu/primes",
  },
  {
    id: "p13",
    title: "Stanford Summer Humanities Institute",
    university: "Stanford University",
    location: "Stanford, CA",
    country: "USA",
    level: "High School",
    category: "Summer",
    fields: ["Humanities"],
    format: "Offline",
    duration: "3 Weeks",
    tuition: 0,
    tags: ["Humanities", "Philosophy", "Writing"],
    eligibility: ["International", "Domestic"],
    description: "Explore the big questions of humanity through intensive seminars with Stanford professors in fields like philosophy, history, and literature.",
    special_features: ["Professor-led seminars", "University-level writing", "Residential experience"],
    noticable_facts: ["Financial aid available", "Intensive academic exploration"],
    apply_link: "https://summerhumanities.stanford.edu",
  },
  {
    id: "p14",
    title: "RSI (Research Science Institute)",
    university: "MIT & CEE",
    location: "Cambridge, MA",
    country: "USA",
    level: "High School",
    category: "Research",
    fields: ["STEM"],
    format: "Offline",
    duration: "6 Weeks",
    tuition: 0,
    tags: ["STEM Research", "Competition", "Cost-Free"],
    eligibility: ["International", "Domestic"],
    description: "The first cost-free to students, summer science & engineering program to combine on-campus course work in scientific theory with off-campus work in science and technology research.",
    special_features: ["Full scholarship", "Research with leading scientists", "Mentorship from MIT/Harvard faculty"],
    noticable_facts: ["Prestigious 'Rickoids' alumni network", "Extremely low acceptance rate"],
    apply_link: "https://cee.org/rsi",
  },
  {
    id: "p15",
    title: "KAUST Discovery Scholars Program",
    university: "KAUST",
    location: "Thuwal, Saudi Arabia",
    country: "Saudi Arabia",
    level: "Undergraduate",
    category: "Research",
    fields: ["STEM"],
    format: "Offline",
    duration: "8 Weeks",
    tuition: 0,
    tags: ["STEM", "Research", "Fully Funded"],
    eligibility: ["International"],
    description: "A prestigious scholarship and research program for outstanding undergraduate students to experience world-class research at KAUST.",
    special_features: ["Full travel & housing coverage", "Stipend included", "Cutting-edge lab access"],
    noticable_facts: ["Global cohort", "Fast-track to Graduate school"],
    apply_link: "https://kaust.edu.sa",
  },
  {
    id: "p16",
    title: "QuestBridge College Prep Scholars",
    university: "QuestBridge",
    location: "USA / Online",
    country: "USA",
    level: "High School",
    category: "University",
    fields: ["Interdisciplinary"],
    format: "Hybrid",
    duration: "Summer",
    tuition: 0,
    tags: ["Full Scholarship", "College Prep"],
    eligibility: ["Domestic"],
    description: "Provides high-achieving, low-income students with tools and opportunities to excel in the college admissions process.",
    special_features: ["Full scholarships to summer programs", "Admissions counseling", "QuestBridge network access"],
    noticable_facts: ["Pathway to top-tier universities", "Focus on financial accessibility"],
    apply_link: "https://questbridge.org",
  },
  {
    id: "p17",
    title: "Carnegie Mellon SAMS",
    university: "Carnegie Mellon University",
    location: "Pittsburgh, PA",
    country: "USA",
    level: "High School",
    category: "Summer",
    fields: ["STEM"],
    format: "Offline",
    duration: "6 Weeks",
    tuition: 0,
    tags: ["STEM", "Full Scholarship"],
    eligibility: ["Domestic"],
    description: "Summer Academy for Math and Science. Provides students from underrepresented backgrounds with the opportunity to explore STEM fields.",
    special_features: ["No cost for tuition/room/board", "Project-based learning", "Mentorship from CMU faculty"],
    noticable_facts: ["Focus on diversity in STEM", "Intensive academic curriculum"],
    apply_link: "https://cmu.edu/pre-college/sams",
  },
  {
    id: "p18",
    title: "NSF REU",
    university: "National Science Foundation",
    location: "USA",
    country: "USA",
    level: "Undergraduate",
    category: "Research",
    fields: ["STEM"],
    format: "Offline",
    duration: "10 Weeks",
    tuition: 0,
    tags: ["STEM", "Paid", "Funded"],
    eligibility: ["Domestic"],
    description: "Research Experiences for Undergraduates. Supports active research participation by undergraduate students in any of the areas of research funded by the NSF.",
    special_features: ["Stipend provided", "Housing and travel support", "Direct research experience"],
    noticable_facts: ["Thousands of sites across the US", "Critical for PhD applications"],
    apply_link: "https://nsf.gov/reu",
  },
  {
    id: "p19",
    title: "NASA OSTEM Internships",
    university: "NASA",
    location: "Multiple Sites, USA",
    country: "USA",
    level: "High School",
    category: "Internship",
    fields: ["STEM"],
    format: "Offline",
    duration: "8-10 Weeks",
    tuition: 0,
    tags: ["STEM", "NASA", "Paid"],
    eligibility: ["Domestic"],
    description: "NASA Office of STEM Engagement internships provide students with the opportunity to participate in either research or other experiential learning.",
    special_features: ["Paid internships", "Work at NASA centers", "Real mission involvement"],
    noticable_facts: ["Highly competitive", "Hands-on engineering projects"],
    apply_link: "https://intern.nasa.gov",
  },
  {
    id: "p20",
    title: "CERN Summer Student Program",
    university: "CERN",
    location: "Geneva, Switzerland",
    country: "Switzerland",
    level: "Undergraduate",
    category: "Summer",
    fields: ["STEM"],
    format: "Offline",
    duration: "8-13 Weeks",
    tuition: 0,
    tags: ["Physics", "Funded"],
    eligibility: ["International"],
    description: "Experience CERN's unique scientific environment. Join a research team and attend lectures by renowned scientists.",
    special_features: ["Stipend included", "Lecture series by experts", "Visits to CERN accelerators"],
    noticable_facts: ["International physics hub", "Largest particle physics lab"],
    apply_link: "https://careers.cern/summer",
  },
  {
    id: "p21",
    title: "Google Summer of Code",
    university: "Google Open Source",
    location: "Online / Global",
    country: "Global",
    level: "Undergraduate",
    category: "Internship",
    fields: ["STEM"],
    format: "Online",
    duration: "12 Weeks",
    tuition: 0,
    tags: ["Open Source", "Coding", "Stipend"],
    eligibility: ["International", "Domestic"],
    description: "A global, online program focused on bringing new contributors into open source software development.",
    special_features: ["Stipend for contributions", "Work with real OSS orgs", "Expert mentorship"],
    noticable_facts: ["Remote-first", "Highly valued by tech companies"],
    apply_link: "https://summerofcode.withgoogle.com",
  },
  {
    id: "p22",
    title: "MIT Summer Research Program (MSRP)",
    university: "MIT",
    location: "Cambridge, MA",
    country: "USA",
    level: "Undergraduate",
    category: "Research",
    fields: ["STEM", "Humanities"],
    format: "Offline",
    duration: "9 Weeks",
    tuition: 0,
    tags: ["Research", "Fully Funded", "MIT"],
    eligibility: ["Domestic"],
    description: "MSRP seeks to identify talented sophomores and juniors from across the US who are interested in pursuing a PhD at MIT.",
    special_features: ["Round-trip travel", "University housing", "Weekly stipend"],
    noticable_facts: ["Bridge to MIT PhD", "Intensive faculty-led research"],
    apply_link: "https://oge.mit.edu/msrp",
  },
  {
    id: "p23",
    title: "Caltech SURF",
    university: "Caltech",
    location: "Pasadena, CA",
    country: "USA",
    level: "Undergraduate",
    category: "Research",
    fields: ["STEM"],
    format: "Offline",
    duration: "10 Weeks",
    tuition: 0,
    tags: ["Research", "STEM", "Paid"],
    eligibility: ["International", "Domestic"],
    description: "Summer Undergraduate Research Fellowships. Introduces students to research under the guidance of Caltech faculty.",
    special_features: ["Direct faculty mentorship", "Oral presentations", "Published technical reports"],
    noticable_facts: ["Prestigious research foundation", "Strong focus on innovation"],
    apply_link: "https://sfp.caltech.edu/surf",
  },
  {
    id: "p24",
    title: "Stanford CURIS",
    university: "Stanford University",
    location: "Stanford, CA",
    country: "USA",
    level: "Undergraduate",
    category: "Research",
    fields: ["STEM"],
    format: "Offline",
    duration: "10 Weeks",
    tuition: 0,
    tags: ["Computer Science", "Research", "Stipend"],
    eligibility: ["International", "Domestic"],
    description: "Undergraduate Research in Computer Science. Provides Stanford students and visitors with research opportunities in the CS department.",
    special_features: ["AI & Robotics research", "Systems & Networking", "Stipend support"],
    noticable_facts: ["Silicon Valley integration", "Leading-edge CS research"],
    apply_link: "https://cs.stanford.edu/curis",
  },
  {
    id: "p25",
    title: "Oxford UNIQ Summer School",
    university: "University of Oxford",
    location: "Oxford, UK",
    country: "UK",
    level: "High School",
    category: "Summer",
    fields: ["STEM", "Humanities"],
    format: "Offline",
    duration: "1 Week",
    tuition: 0,
    tags: ["Oxford", "Access", "Free"],
    eligibility: ["Domestic"],
    description: "Gives students from state schools in the UK a chance to experience life at Oxford and learn about the application process.",
    special_features: ["Residential at an Oxford college", "Tutorial-style teaching", "Application support"],
    noticable_facts: ["Free of charge", "Aimed at underrepresented groups"],
    apply_link: "https://uniq.ox.ac.uk",
  },
  {
    id: "p26",
    title: "Cambridge Sutton Trust Summer School",
    university: "University of Cambridge",
    location: "Cambridge, UK",
    country: "UK",
    level: "High School",
    category: "Summer",
    fields: ["STEM", "Humanities", "Business"],
    format: "Offline",
    duration: "1 Week",
    tuition: 0,
    tags: ["Cambridge", "Social Mobility", "Free"],
    eligibility: ["Domestic"],
    description: "Subject-specific summer schools for high-achieving students from low-income backgrounds.",
    special_features: ["Experience Cambridge supervisions", "Meet current students", "Free accommodation & food"],
    noticable_facts: ["Proven to boost admission rates", "High-quality academic content"],
    apply_link: "https://undergraduate.study.cam.ac.uk",
  },
  {
    id: "p27",
    title: "ETH Zurich Summer Research Fellowship",
    university: "ETH Zurich",
    location: "Zurich, Switzerland",
    country: "Switzerland",
    level: "Undergraduate",
    category: "Research",
    fields: ["STEM"],
    format: "Offline",
    duration: "2 Months",
    tuition: 0,
    tags: ["CS", "Research", "Europe"],
    eligibility: ["International"],
    description: "Fellowship for undergraduate and graduate students in Computer Science to gain research experience at ETH Zurich.",
    special_features: ["Monthly stipend", "Travel costs covered", "Social program in Switzerland"],
    noticable_facts: ["World's top CS labs", "Mountain-side campus"],
    apply_link: "https://inf.ethz.ch/studies/summer-research-fellowship",
  },
  {
    id: "p28",
    title: "EPFL Excellence Fellowships",
    university: "EPFL",
    location: "Lausanne, Switzerland",
    country: "Switzerland",
    level: "Undergraduate",
    category: "Research",
    fields: ["STEM"],
    format: "Offline",
    duration: "3 Months",
    tuition: 0,
    tags: ["Research", "Fully Funded"],
    eligibility: ["International"],
    description: "Summer internships for students from around the world to participate in research projects in Life Sciences and Engineering.",
    special_features: ["Housing allowance", "Travel stipend", "Social activities"],
    noticable_facts: ["French-speaking Switzerland", "Leading engineering school"],
    apply_link: "https://sv.epfl.ch/summer-internship",
  },
  {
    id: "p29",
    title: "RISE Germany (DAAD)",
    university: "DAAD / German Unis",
    location: "Germany",
    country: "Germany",
    level: "Undergraduate",
    category: "Research",
    fields: ["STEM"],
    format: "Offline",
    duration: "3 Months",
    tuition: 0,
    tags: ["STEM", "Research", "Stipend"],
    eligibility: ["International"],
    description: "Research Internships in Science and Engineering. Matches North American and UK students with PhD mentors in Germany.",
    special_features: ["Monthly stipend", "Health insurance", "Travel allowance"],
    noticable_facts: ["Learn German culture", "Professional network in Europe"],
    apply_link: "https://daad.de/rise",
  },
  {
    id: "p30",
    title: "Google STEP Internship",
    university: "Google",
    location: "Global",
    country: "Global",
    level: "Undergraduate",
    category: "Internship",
    fields: ["STEM"],
    format: "Offline",
    duration: "12 Weeks",
    tuition: 0,
    tags: ["CS", "Google", "Paid"],
    eligibility: ["International", "Domestic"],
    description: "Student Training in Engineering Program. Designed for first and second-year undergraduate students with a passion for CS.",
    special_features: ["Technical training", "Project work with Googlers", "Professional development"],
    noticable_facts: ["Pipeline to regular internships", "Highly sought after"],
    apply_link: "https://buildyourfuture.withgoogle.com",
  },
  {
    id: "p31",
    title: "Microsoft Explore Program",
    university: "Microsoft",
    location: "Redmond, WA",
    country: "USA",
    level: "Undergraduate",
    category: "Internship",
    fields: ["STEM"],
    format: "Offline",
    duration: "12 Weeks",
    tuition: 0,
    tags: ["CS", "PM", "Paid"],
    eligibility: ["Domestic"],
    description: "A rotational internship program designed for first and second-year students to explore Software Engineering and Program Management.",
    special_features: ["Rotational experience", "Mentorship", "Housing stipend"],
    noticable_facts: ["End-to-end product view", "Great for undecided majors"],
    apply_link: "https://careers.microsoft.com",
  },
  {
    id: "p32",
    title: "Meta University",
    university: "Meta",
    location: "Menlo Park, CA",
    country: "USA",
    level: "Undergraduate",
    category: "Internship",
    fields: ["STEM", "Business"],
    format: "Offline",
    duration: "10 Weeks",
    tuition: 0,
    tags: ["Engineering", "Analytics", "Paid"],
    eligibility: ["Domestic"],
    description: "A training-based internship program that enables students from underrepresented communities to get early career experience.",
    special_features: ["Skills training", "Project work", "Mentorship"],
    noticable_facts: ["Diversity focused", "Hands-on product building"],
    apply_link: "https://metacareers.com/university",
  },
  {
    id: "p33",
    title: "Bloomberg Software Engineering",
    university: "Bloomberg LP",
    location: "NYC / London",
    country: "USA / UK",
    level: "Undergraduate",
    category: "Internship",
    fields: ["STEM"],
    format: "Offline",
    duration: "12 Weeks",
    tuition: 0,
    tags: ["Finance", "Coding", "Paid"],
    eligibility: ["International", "Domestic"],
    description: "Build the tools that drive the world's financial markets. Focus on low-latency, high-availability systems.",
    special_features: ["Real-time data tech", "Professional training", "Collaborative culture"],
    noticable_facts: ["High compensation", "Strong focus on C++ and JS"],
    apply_link: "https://bloomberg.com/careers",
  },
  {
    id: "p34",
    title: "Goldman Sachs Summer Analyst",
    university: "Goldman Sachs",
    location: "Global",
    country: "Global",
    level: "Undergraduate",
    category: "Internship",
    fields: ["Business", "STEM"],
    format: "Offline",
    duration: "10 Weeks",
    tuition: 0,
    tags: ["Finance", "Banking", "Paid"],
    eligibility: ["International", "Domestic"],
    description: "A ten-week program for students to experience the day-to-day life of a financial analyst in a global firm.",
    special_features: ["Client project involvement", "Networking events", "Training sessions"],
    noticable_facts: ["Elite banking entry", "High conversion to full-time"],
    apply_link: "https://goldmansachs.com/careers",
  },
  {
    id: "p35",
    title: "JPMorgan Summer Analyst",
    university: "JPMorgan Chase",
    location: "Global",
    country: "Global",
    level: "Undergraduate",
    category: "Internship",
    fields: ["Business", "STEM"],
    format: "Offline",
    duration: "10 Weeks",
    tuition: 0,
    tags: ["Finance", "Tech", "Paid"],
    eligibility: ["International", "Domestic"],
    description: "Explore career paths in Corporate & Investment Bank, Asset Management, or Commercial Banking.",
    special_features: ["Intensive training", "Real deal exposure", "Leadership speakers"],
    noticable_facts: ["Largest US bank", "Global reach"],
    apply_link: "https://jpmorganchase.com/careers",
  },
  {
    id: "p36",
    title: "World Bank Internship",
    university: "World Bank Group",
    location: "Washington D.C.",
    country: "USA",
    level: "Graduate",
    category: "Internship",
    fields: ["Humanities", "Business"],
    format: "Hybrid",
    duration: "3-4 Months",
    tuition: 0,
    tags: ["Policy", "Development", "Paid"],
    eligibility: ["International"],
    description: "Opportunities for highly motivated individuals to be exposed to the mission and work of the World Bank Group.",
    special_features: ["Global impact research", "Policy analysis", "International team"],
    noticable_facts: ["Requires Master's or PhD", "Focus on developing economies"],
    apply_link: "https://worldbank.org/internships",
  },
  {
    id: "p37",
    title: "United Nations Internship",
    university: "United Nations",
    location: "NY / Geneva / Vienna",
    country: "Global",
    level: "Graduate",
    category: "Internship",
    fields: ["Humanities", "Law"],
    format: "Hybrid",
    duration: "2-6 Months",
    tuition: 0,
    tags: ["Diplomacy", "International Law"],
    eligibility: ["International"],
    description: "Get a first-hand look at the day-to-day working environment of the UN and its diverse departments.",
    special_features: ["Exposure to high-level meetings", "Policy drafting", "International networking"],
    noticable_facts: ["Often unpaid (some exceptions)", "Highly competitive"],
    apply_link: "https://careers.un.org",
  },
  {
    id: "p38",
    title: "WHO Internship Programme",
    university: "World Health Org",
    location: "Geneva / Regional",
    country: "Global",
    level: "Graduate",
    category: "Internship",
    fields: ["Health", "STEM"],
    format: "Hybrid",
    duration: "6-24 Weeks",
    tuition: 0,
    tags: ["Public Health", "Global Policy"],
    eligibility: ["International"],
    description: "Provides an opportunity for students to gain insight into the work of WHO and participate in international health projects.",
    special_features: ["Global health monitoring", "Technical support", "Policy research"],
    noticable_facts: ["Focus on global health equity", "Diverse technical fields"],
    apply_link: "https://who.int/careers",
  },
  {
    id: "p39",
    title: "UNICEF Internship Program",
    university: "UNICEF",
    location: "Global",
    country: "Global",
    level: "Graduate",
    category: "Internship",
    fields: ["Humanities", "Health"],
    format: "Hybrid",
    duration: "6-26 Weeks",
    tuition: 0,
    tags: ["Children Rights", "Development"],
    eligibility: ["International"],
    description: "Opportunities for students to gain professional work experience in UNICEF's work for children.",
    special_features: ["Field office exposure", "Data collection", "Rights advocacy"],
    noticable_facts: ["Focus on child welfare", "Global presence"],
    apply_link: "https://unicef.org/careers",
  },
  {
    id: "p40",
    title: "IMF Fund Internship",
    university: "Int. Monetary Fund",
    location: "Washington D.C.",
    country: "USA",
    level: "Graduate",
    category: "Internship",
    fields: ["Business", "Humanities"],
    format: "Offline",
    duration: "10-12 Weeks",
    tuition: 0,
    tags: ["Economics", "Finance", "Paid"],
    eligibility: ["International"],
    description: "Intensive research project for PhD students in economics or related fields.",
    special_features: ["Work with senior economists", "Publication potential", "Stipend and travel"],
    noticable_facts: ["Elite economic research", "Prestigious PhD track"],
    apply_link: "https://imf.org/jobs",
  },
  {
    id: "p41",
    title: "Erasmus+ Traineeships",
    university: "European Union",
    location: "Europe",
    country: "Europe",
    level: "Undergraduate",
    category: "Internship",
    fields: ["All"],
    format: "Offline",
    duration: "2-12 Months",
    tuition: 0,
    tags: ["Exchange", "EU", "Stipend"],
    eligibility: ["International"],
    description: "Support for students to do an internship abroad in a company or any other relevant workplace in Europe.",
    special_features: ["Erasmus+ grant", "Cultural exchange", "Professional recognition"],
    noticable_facts: ["Open to EU and partner countries", "Broad subject range"],
    apply_link: "https://erasmus-plus.ec.europa.eu",
  },
  {
    id: "p51",
    title: "Jackson Laboratory Summer Student Program",
    university: "The Jackson Laboratory",
    location: "Bar Harbor, ME",
    country: "USA",
    level: "Undergraduate",
    category: "Research",
    fields: ["STEM"],
    format: "Offline",
    duration: "10 Weeks",
    tuition: 0,
    tags: ["Genetics", "Bioinformatics", "Paid"],
    eligibility: ["Domestic"],
    description: "Participate in independent research under the guidance of a staff scientist. Focus on genetics, genomics, and bioinformatics.",
    special_features: ["Individual research project", "Professional development", "Stipend and housing provided"],
    noticable_facts: ["Focus on mammalian genetics", "Beautiful coastal Maine campus"],
    apply_link: "https://jax.org/education-and-learning/high-school-students-and-undergraduates/summer-student-program",
  },
  {
    id: "p52",
    title: "NIH Summer Internship Program (SIP)",
    university: "National Institutes of Health",
    location: "Bethesda, MD / Global",
    country: "USA",
    level: "High School",
    category: "Internship",
    fields: ["STEM", "Medicine"],
    format: "Offline",
    duration: "8 Weeks",
    tuition: 0,
    tags: ["Biomedical", "Health", "Paid"],
    eligibility: ["Domestic"],
    description: "Provides an opportunity for students to spend a summer working at the NIH side-by-side with some of the world's leading scientists.",
    special_features: ["Work in NIH laboratories", "Career development workshops", "Scientific lectures"],
    noticable_facts: ["World's largest biomedical research institution", "Multiple locations available"],
    apply_link: "https://training.nih.gov/programs/sip",
  },
  {
    id: "p53",
    title: "TASP (Telluride Association Summer Seminar)",
    university: "Telluride Association",
    location: "Various (Cornell/Maryland)",
    country: "USA",
    level: "High School",
    category: "Summer",
    fields: ["Humanities", "Social Sciences"],
    format: "Offline",
    duration: "6 Weeks",
    tuition: 0,
    tags: ["Critical Thinking", "Humanities", "Free"],
    eligibility: ["International", "Domestic"],
    description: "Free six-week educational program for high school juniors. Focuses on critical thinking and democratic community living.",
    special_features: ["Full scholarship", "Seminar-style learning", "Student-run governance"],
    noticable_facts: ["One of the most prestigious humanities programs", "Intense intellectual rigor"],
    apply_link: "https://tellurideassociation.org",
  },
  {
    id: "p54",
    title: "Interlochen Arts Camp",
    university: "Interlochen Center for the Arts",
    location: "Interlochen, MI",
    country: "USA",
    level: "High School",
    category: "Summer",
    fields: ["Arts"],
    format: "Offline",
    duration: "1-6 Weeks",
    tuition: 6000,
    tags: ["Music", "Visual Arts", "Theater"],
    eligibility: ["International", "Domestic"],
    description: "A world-renowned arts program where students receive intensive training in their chosen artistic discipline.",
    special_features: ["Performance opportunities", "Masterclasses with professionals", "Creative community"],
    noticable_facts: ["Alumni include many famous artists", "Beautiful wooded campus"],
    apply_link: "https://camp.interlochen.org",
  },
  {
    id: "p55",
    title: "Tanglewood Institute (BUTI)",
    university: "Boston University",
    location: "Lenox, MA",
    country: "USA",
    level: "High School",
    category: "Summer",
    fields: ["Arts"],
    format: "Offline",
    duration: "2-6 Weeks",
    tuition: 5000,
    tags: ["Classical Music", "Orchestra", "Voice"],
    eligibility: ["International", "Domestic"],
    description: "A premier summer training program for young musicians, located at the summer home of the Boston Symphony Orchestra.",
    special_features: ["Work with BSO members", "Performance at Tanglewood", "Intensive musical training"],
    noticable_facts: ["World-class musical environment", "Legacy of excellence"],
    apply_link: "https://bu.edu/tanglewood",
  },
  {
    id: "p56",
    title: "Hampshire College Summer Math (HCSSiM)",
    university: "Hampshire College",
    location: "Amherst, MA",
    country: "USA",
    level: "High School",
    category: "Summer",
    fields: ["Mathematics"],
    format: "Offline",
    duration: "6 Weeks",
    tuition: 0,
    tags: ["Mathematics", "Math Camp", "Selective"],
    eligibility: ["International", "Domestic"],
    description: "An intensive six-week encounter with abstract mathematics for talented high school students.",
    special_features: ["Proof-based learning", "Close interaction with faculty", "Collaborative atmosphere"],
    noticable_facts: ["Unique 'Interesting Test' application", "Focus on mathematical discovery"],
    apply_link: "https://hcssim.org",
  },
  {
    id: "p57",
    title: "Bank of America Student Leaders",
    university: "Bank of America",
    location: "Local Market / Washington DC",
    country: "USA",
    level: "High School",
    category: "Internship",
    fields: ["Business", "Leadership"],
    format: "Offline",
    duration: "8 Weeks",
    tuition: 0,
    tags: ["Leadership", "Community Service", "Paid"],
    eligibility: ["Domestic"],
    description: "Connects community-minded high school juniors and seniors to employment, skills development, and service.",
    special_features: ["Paid internship at a local nonprofit", "National Student Leadership Summit", "Community leadership focus"],
    noticable_facts: ["Highly selective", "Full travel and expenses paid"],
    apply_link: "https://about.bankofamerica.com/en-us/what-guides-us/student-leaders.html",
  },
  {
    id: "p58",
    title: "NSLI-Y (National Security Language Initiative)",
    university: "U.S. Department of State",
    location: "Global",
    country: "Global",
    level: "High School",
    category: "Summer",
    fields: ["Humanities"],
    format: "Offline",
    duration: "6-8 Weeks",
    tuition: 0,
    tags: ["Language", "Cultural Exchange", "Fully Funded"],
    eligibility: ["Domestic"],
    description: "Immersive language learning programs abroad for American high school students to learn critical languages.",
    special_features: ["Full scholarship", "Host family stay", "Intensive language instruction"],
    noticable_facts: ["Covers Arabic, Chinese, Hindi, Indonesian, Korean, Persian, Russian, and Turkish", "Government-sponsored"],
    apply_link: "https://nsliforyouth.org",
  },
  {
    id: "p59",
    title: "CIEE Global Navigator High School",
    university: "CIEE",
    location: "Global",
    country: "Global",
    level: "High School",
    category: "Summer",
    fields: ["Humanities", "STEM", "Arts"],
    format: "Offline",
    duration: "3-4 Weeks",
    tuition: 5000,
    tags: ["Study Abroad", "Language", "Service"],
    eligibility: ["International", "Domestic"],
    description: "Explore a new culture, learn a language, or engage in community service through study abroad programs.",
    special_features: ["Multiple subject tracks", "Language immersion", "Service-learning projects"],
    noticable_facts: ["Merit and need-based scholarships available", "Over 40 destinations"],
    apply_link: "https://ciee.org/go-abroad/high-school-summer-abroad",
  },
  {
    id: "p60",
    title: "International Mathematical Olympiad (IMO)",
    university: "IMO Board",
    location: "Global",
    country: "Global",
    level: "High School",
    category: "Competition",
    fields: ["Mathematics"],
    format: "Offline",
    duration: "2 Weeks",
    tuition: 0,
    tags: ["Mathematics", "Prestige", "Global"],
    eligibility: ["International"],
    description: "The World Championship Mathematics Competition for High School students.",
    special_features: ["Highest level of math competition", "Global networking", "Medal recognition"],
    noticable_facts: ["Extremely challenging problems", "Participating teams from over 100 countries"],
    apply_link: "https://imo-official.org",
  },
  {
    id: "p61",
    title: "International Olympiad in Informatics (IOI)",
    university: "IOI Board",
    location: "Global",
    country: "Global",
    level: "High School",
    category: "Competition",
    fields: ["STEM"],
    format: "Offline",
    duration: "1 Week",
    tuition: 0,
    tags: ["Coding", "Algorithms", "Prestige"],
    eligibility: ["International"],
    description: "The premier international competitive programming competition for secondary school students.",
    special_features: ["Algorithmic problem solving", "Global recognition", "Tech networking"],
    noticable_facts: ["Focus on complex algorithms", "Supported by major tech companies"],
    apply_link: "https://ioinformatics.org",
  },
  {
    id: "p62",
    title: "Regeneron Science Talent Search (STS)",
    university: "Society for Science",
    location: "Washington D.C.",
    country: "USA",
    level: "High School",
    category: "Competition",
    fields: ["STEM"],
    format: "Hybrid",
    duration: "Year-long",
    tuition: 0,
    tags: ["Research", "STEM", "Awards"],
    eligibility: ["Domestic"],
    description: "The nation's oldest and most prestigious science and math competition for high school seniors.",
    special_features: ["Substantial cash awards", "Interaction with top scientists", "Prestige in college admissions"],
    noticable_facts: ["Alumni include Nobel Prize winners", "Focus on original research"],
    apply_link: "https://societyforscience.org/regeneron-sts",
  },
  {
    id: "p63",
    title: "Google Code-in (Legacy)",
    university: "Google Open Source",
    location: "Online",
    country: "Global",
    level: "High School",
    category: "Competition",
    fields: ["STEM"],
    format: "Online",
    duration: "7 Weeks",
    tuition: 0,
    tags: ["Open Source", "Coding", "Rewards"],
    eligibility: ["International", "Domestic"],
    description: "A contest to introduce pre-university students to open source software development.",
    special_features: ["Small task-based contributions", "Mentorship from OSS projects", "Google prizes"],
    noticable_facts: ["Accessible entry into open source", "Global community"],
    apply_link: "https://codein.withgoogle.com",
  },
  {
    id: "p64",
    title: "Blue Stamp Engineering",
    university: "BSE Global",
    location: "Online / NY / CA",
    country: "USA",
    level: "High School",
    category: "Summer",
    fields: ["STEM"],
    format: "Hybrid",
    duration: "6 Weeks",
    tuition: 4500,
    tags: ["Engineering", "Hardware", "Robotics"],
    eligibility: ["International", "Domestic"],
    description: "A hands-on engineering program where students build a project of their own choosing from scratch.",
    special_features: ["Individual engineering project", "Technical skill building", "Career mentorship"],
    noticable_facts: ["Focus on physical builds", "Great for portfolios"],
    apply_link: "https://bluestampengineering.com",
  },
  {
    id: "p65",
    title: "Polygence Research Program",
    university: "Polygence",
    location: "Online / Global",
    country: "USA",
    level: "High School",
    category: "Research",
    fields: ["All"],
    format: "Online",
    duration: "10-20 Weeks",
    tuition: 2500,
    tags: ["Mentorship", "Research", "Independent"],
    eligibility: ["International", "Domestic"],
    description: "Matches high school students with expert mentors to conduct personalized research projects.",
    special_features: ["1-on-1 mentorship", "Personalized project scope", "Publication support"],
    noticable_facts: ["Broad subject range", "Flexible scheduling"],
    apply_link: "https://polygence.org",
  },
  {
    id: "p66",
    title: "Indigo Research",
    university: "Indigo Research",
    location: "Online / Global",
    country: "USA",
    level: "High School",
    category: "Research",
    fields: ["STEM", "Humanities", "Business"],
    format: "Online",
    duration: "12 Weeks",
    tuition: 3500,
    tags: ["Mentorship", "Publication", "Ivy League"],
    eligibility: ["International", "Domestic"],
    description: "Connects students with mentors from world-class universities to conduct high-level research.",
    special_features: ["Academic publication guidance", "Network with researchers", "Certificate of completion"],
    noticable_facts: ["Mentors from top global universities", "Rigorous academic standard"],
    apply_link: "https://indigoresearch.org",
  },
  {
    id: "p67",
    title: "Smithsonian Internships",
    university: "Smithsonian Institution",
    location: "Washington D.C. / Global",
    country: "USA",
    level: "Undergraduate",
    category: "Internship",
    fields: ["Humanities", "Arts", "STEM"],
    format: "Hybrid",
    duration: "10 Weeks",
    tuition: 0,
    tags: ["Museums", "History", "Research"],
    eligibility: ["International", "Domestic"],
    description: "Internships at the world's largest museum, education, and research complex.",
    special_features: ["Curatorial research", "Museum management", "Archive work"],
    noticable_facts: ["Diverse subject areas", "Historic institutions"],
    apply_link: "https://smithsonianofi.com",
  },
  {
    id: "p68",
    title: "Walt Disney World Internship",
    university: "Disney",
    location: "Orlando, FL",
    country: "USA",
    level: "Undergraduate",
    category: "Internship",
    fields: ["Business", "Arts", "STEM"],
    format: "Offline",
    duration: "4-6 Months",
    tuition: 0,
    tags: ["Hospitality", "Entertainment", "Paid"],
    eligibility: ["International", "Domestic"],
    description: "Gain hands-on experience at Disney Parks & Resorts in roles ranging from park operations to engineering.",
    special_features: ["Disney College Program", "Professional development", "Park access"],
    noticable_facts: ["Global hospitality standard", "High networking value"],
    apply_link: "https://jobs.disneycareers.com",
  },
  {
    id: "p69",
    title: "United Nations Volunteers",
    university: "United Nations",
    location: "Global",
    country: "Global",
    level: "Graduate",
    category: "Internship",
    fields: ["Humanities", "Health"],
    format: "Offline",
    duration: "6-12 Months",
    tuition: 0,
    tags: ["Development", "Peace", "Volunteer"],
    eligibility: ["International"],
    description: "Contribute to peace and development through volunteerism worldwide with the UN.",
    special_features: ["Living allowance provided", "Global field assignments", "Direct development impact"],
    noticable_facts: ["Requires 2+ years of experience", "Life-changing global work"],
    apply_link: "https://unv.org",
  },
  {
    id: "p70",
    title: "Schwarzman Scholars Summer",
    university: "Tsinghua University",
    location: "Beijing, China",
    country: "China",
    level: "Graduate",
    category: "Summer",
    fields: ["Business", "Humanities", "Leadership"],
    format: "Offline",
    duration: "4 Weeks",
    tuition: 0,
    tags: ["Leadership", "China", "Global Affairs"],
    eligibility: ["International"],
    description: "Intensive summer leadership program for future global leaders to understand China's role in the world.",
    special_features: ["Elite networking", "High-level policy briefings", "Cultural immersion"],
    noticable_facts: ["Fully funded", "Highly competitive"],
    apply_link: "https://schwarzmanscholars.org",
  },
  {
    id: "p71",
    title: "Princeton Bridge Year",
    university: "Princeton University",
    location: "Global (Various)",
    country: "Global",
    level: "High School",
    category: "University",
    fields: ["Humanities", "Interdisciplinary"],
    format: "Offline",
    duration: "9 Months",
    tuition: 0,
    tags: ["Gap Year", "Service", "Immersive"],
    eligibility: ["Domestic"],
    description: "A tuition-free program that allows incoming freshmen to spend a year engaged in community service abroad.",
    special_features: ["Full scholarship", "Community service immersion", "Language learning"],
    noticable_facts: ["Alternative to starting college immediately", "Deep cultural engagement"],
    apply_link: "https://bridgeyear.princeton.edu",
  },
  {
    id: "p72",
    title: "Stanford Summer Session",
    university: "Stanford University",
    location: "Stanford, CA",
    country: "USA",
    level: "High School",
    category: "Summer",
    fields: ["All"],
    format: "Hybrid",
    duration: "8 Weeks",
    tuition: 15000,
    tags: ["Stanford", "College Credit"],
    eligibility: ["International", "Domestic"],
    description: "Join the Stanford community for a summer of high-intensity learning and research.",
    special_features: ["Take real Stanford courses", "Earn university credit", "Campus activities"],
    noticable_facts: ["Rigorous academic standards", "Global student cohort"],
    apply_link: "https://summer.stanford.edu",
  },
  {
    id: "p73",
    title: "Columbia Summer Immersion",
    university: "Columbia University",
    location: "NYC / Online",
    country: "USA",
    level: "High School",
    category: "Summer",
    fields: ["STEM", "Humanities", "Arts"],
    format: "Hybrid",
    duration: "3 Weeks",
    tuition: 6000,
    tags: ["NYC", "Ivy League", "Immersion"],
    eligibility: ["International", "Domestic"],
    description: "Experience university life in New York City while exploring academic interests in depth.",
    special_features: ["NYC-based learning", "Faculty-led seminars", "College preparation"],
    noticable_facts: ["Intense subject focus", "Ivy League environment"],
    apply_link: "https://precollege.sps.columbia.edu",
  },
  {
    id: "p74",
    title: "Brown Pre-College Programs",
    university: "Brown University",
    location: "Providence, RI",
    country: "USA",
    level: "High School",
    category: "Summer",
    fields: ["STEM", "Humanities", "Arts"],
    format: "Hybrid",
    duration: "1-4 Weeks",
    tuition: 4500,
    tags: ["Brown", "Academic Discovery"],
    eligibility: ["International", "Domestic"],
    description: "Courses designed to prepare students for the rigors of university learning and explore new subjects.",
    special_features: ["No-grades learning", "Diverse course catalog", "Residential experience"],
    noticable_facts: ["Focus on 'The Joy of Learning'", "Over 300 courses"],
    apply_link: "https://precollege.brown.edu",
  },
  {
    id: "p75",
    title: "Georgetown Summer Medical",
    university: "Georgetown University",
    location: "Washington D.C.",
    country: "USA",
    level: "High School",
    category: "Summer",
    fields: ["Medicine"],
    format: "Offline",
    duration: "1 Week",
    tuition: 3000,
    tags: ["Medicine", "Anatomy", "Clinical"],
    eligibility: ["International", "Domestic"],
    description: "A fast-paced immersion into the world of medicine and clinical practice at a top medical center.",
    special_features: ["Anatomy lab tours", "Clinical simulations", "Medical ethics seminars"],
    noticable_facts: ["Hands-on exposure", "Located in the nation's capital"],
    apply_link: "https://summer.georgetown.edu",
  },
  {
    id: "p76",
    title: "Johns Hopkins CTY Summer",
    university: "Johns Hopkins CTY",
    location: "Various / Online",
    country: "USA",
    level: "High School",
    category: "Summer",
    fields: ["STEM", "Humanities"],
    format: "Hybrid",
    duration: "3 Weeks",
    tuition: 5000,
    tags: ["Gifted", "Advanced", "CTY"],
    eligibility: ["International", "Domestic"],
    description: "Rigorous academic programs for advanced learners across various campus locations.",
    special_features: ["Talent search based entry", "Highly advanced curriculum", "Strong peer network"],
    noticable_facts: ["Gold standard for gifted education", "Long-standing history"],
    apply_link: "https://cty.jhu.edu",
  },
  {
    id: "p77",
    title: "Duke Summer Session",
    university: "Duke University",
    location: "Durham, NC",
    country: "USA",
    level: "High School",
    category: "Summer",
    fields: ["STEM", "Humanities"],
    format: "Offline",
    duration: "4 Weeks",
    tuition: 8000,
    tags: ["Duke", "Research", "College Prep"],
    eligibility: ["International", "Domestic"],
    description: "Live and learn at Duke University, participating in credit-bearing or enrichment courses.",
    special_features: ["Duke faculty interaction", "Campus living", "Academic rigor"],
    noticable_facts: ["Top-tier university experience", "Comprehensive social programming"],
    apply_link: "https://summersession.duke.edu",
  },
  {
    id: "p78",
    title: "UChicago Summer Session",
    university: "University of Chicago",
    location: "Chicago, IL",
    country: "USA",
    level: "High School",
    category: "Summer",
    fields: ["Humanities", "STEM", "Social Sciences"],
    format: "Hybrid",
    duration: "3-5 Weeks",
    tuition: 7000,
    tags: ["Critical Inquiry", "Intense"],
    eligibility: ["International", "Domestic"],
    description: "Experience the unique intellectual culture of UChicago through intensive seminars and courses.",
    special_features: ["Inquiry-based learning", "Faculty-led research tracks", "Urban campus life"],
    noticable_facts: ["Focus on 'The Life of the Mind'", "Academic intensity"],
    apply_link: "https://summer.uchicago.edu",
  },
  {
    id: "p79",
    title: "Northwestern NHSI (Cherubs)",
    university: "Northwestern University",
    location: "Evanston, IL",
    country: "USA",
    level: "High School",
    category: "Summer",
    fields: ["Arts", "Humanities"],
    format: "Offline",
    duration: "5 Weeks",
    tuition: 6000,
    tags: ["Theatre", "Film", "Debate"],
    eligibility: ["International", "Domestic"],
    description: "The National High School Institute, affectionately known as 'Cherubs', offers intensive programs in arts and communication.",
    special_features: ["Professional-level training", "Collaborative projects", "Network with industry pros"],
    noticable_facts: ["Elite theatre program", "Legacy of famous alumni"],
    apply_link: "https://nhsi.northwestern.edu",
  },
  {
    id: "p80",
    title: "LSE Summer School",
    university: "London School of Economics",
    location: "London, UK",
    country: "UK",
    level: "Undergraduate",
    category: "Summer",
    fields: ["Business", "Humanities", "Social Sciences"],
    format: "Offline",
    duration: "3 Weeks",
    tuition: 4000,
    tags: ["Economics", "Finance", "London"],
    eligibility: ["International"],
    description: "The largest summer school of its kind in Europe, offering over 100 courses across various social science disciplines.",
    special_features: ["LSE faculty lectures", "Global networking", "London city experience"],
    noticable_facts: ["World's leading social science hub", "High-intensity learning"],
    apply_link: "https://lse.ac.uk/summer-school",
  },
  {
    id: "p81",
    title: "Sciences Po Summer School",
    university: "Sciences Po",
    location: "Paris, France",
    country: "France",
    level: "Undergraduate",
    category: "Summer",
    fields: ["Humanities", "Social Sciences"],
    format: "Offline",
    duration: "4 Weeks",
    tuition: 3500,
    tags: ["International Relations", "Paris"],
    eligibility: ["International"],
    description: "An intensive program in social sciences and French language, held in the heart of Paris.",
    special_features: ["Politics & IR focus", "French language tracks", "Central Paris campus"],
    noticable_facts: ["Elite French institution", "Prestigious political science network"],
    apply_link: "https://sciencespo.fr/summer-school",
  },
  {
    id: "p82",
    title: "HEC Paris Summer School",
    university: "HEC Paris",
    location: "Jouy-en-Josas, France",
    country: "France",
    level: "Undergraduate",
    category: "Summer",
    fields: ["Business"],
    format: "Offline",
    duration: "2 Weeks",
    tuition: 3000,
    tags: ["Business", "Entrepreneurship", "Elite"],
    eligibility: ["International"],
    description: "Intensive business programs focused on innovation, entrepreneurship, and luxury management.",
    special_features: ["Top-tier business faculty", "Project-based learning", "Campus residency"],
    noticable_facts: ["Ranked #1 Business School in Europe", "Global business network"],
    apply_link: "https://hec.edu/summer-school",
  },
  {
    id: "p83",
    title: "Bocconi Summer School",
    university: "Bocconi University",
    location: "Milan, Italy",
    country: "Italy",
    level: "Undergraduate",
    category: "Summer",
    fields: ["Business", "Humanities"],
    format: "Offline",
    duration: "3 Weeks",
    tuition: 2800,
    tags: ["Finance", "Management", "Milan"],
    eligibility: ["International"],
    description: "Explore the intersection of business, law, and economics in the vibrant city of Milan.",
    special_features: ["Case study method", "Company visits", "Social program in Italy"],
    noticable_facts: ["Leading European business school", "Strong focus on international markets"],
    apply_link: "https://unibocconi.eu/summerschool",
  },
  {
    id: "p84",
    title: "Tsinghua Global Summer School",
    university: "Tsinghua University",
    location: "Beijing, China",
    country: "China",
    level: "Undergraduate",
    category: "Summer",
    fields: ["STEM", "Business", "Humanities"],
    format: "Hybrid",
    duration: "2 Weeks",
    tuition: 0,
    tags: ["China", "Innovation", "Global"],
    eligibility: ["International"],
    description: "Focus on innovation, sustainable development, and global leadership in a Chinese context.",
    special_features: ["Tsinghua faculty lectures", "Cultural workshops", "Cross-disciplinary collaboration"],
    noticable_facts: ["Top-ranked university in Asia", "Fully funded for many participants"],
    apply_link: "https://tsinghua.edu.cn",
  },
  {
    id: "p85",
    title: "University of Tokyo GSP",
    university: "University of Tokyo",
    location: "Tokyo, Japan",
    country: "Japan",
    level: "Undergraduate",
    category: "Summer",
    fields: ["STEM", "Humanities"],
    format: "Offline",
    duration: "2 Weeks",
    tuition: 1500,
    tags: ["Japan", "Science", "Cultural"],
    eligibility: ["International"],
    description: "Global Summer Program offering courses in Japanese culture, society, and cutting-edge science.",
    special_features: ["Field trips in Japan", "Laboratory visits", "Interaction with UTokyo students"],
    noticable_facts: ["Prestigious 'Todai' experience", "Japan's leading university"],
    apply_link: "https://u-tokyo.ac.jp",
  },
  {
    id: "p86",
    title: "SNU Summer Program",
    university: "Seoul National University",
    location: "Seoul, South Korea",
    country: "South Korea",
    level: "Undergraduate",
    category: "Summer",
    fields: ["Humanities", "STEM", "Business"],
    format: "Offline",
    duration: "5 Weeks",
    tuition: 2500,
    tags: ["Korea", "Culture", "Global"],
    eligibility: ["International"],
    description: "Comprehensive summer program exploring Korean language, history, and modern technology.",
    special_features: ["Seoul city tours", "K-Pop and K-Drama workshops", "Academic exchange"],
    noticable_facts: ["South Korea's top university", "Modern high-tech campus"],
    apply_link: "https://snu.ac.kr",
  },
  {
    id: "p87",
    title: "NTU Summer Program",
    university: "Nanyang Technological Univ",
    location: "Singapore",
    country: "Singapore",
    level: "Undergraduate",
    category: "Summer",
    fields: ["STEM", "Business"],
    format: "Offline",
    duration: "4 Weeks",
    tuition: 3000,
    tags: ["Singapore", "Technology", "Innovation"],
    eligibility: ["International"],
    description: "Focus on innovation and entrepreneurship in the heart of Asia's tech hub.",
    special_features: ["Incubator visits", "Project pitch competition", "Sustainable campus life"],
    noticable_facts: ["World's most beautiful campus", "Top engineering focus"],
    apply_link: "https://ntu.edu.sg",
  },
  {
    id: "p88",
    title: "NUS Enterprise Summer",
    university: "National Univ of Singapore",
    location: "Singapore",
    country: "Singapore",
    level: "Undergraduate",
    category: "Summer",
    fields: ["Business"],
    format: "Offline",
    duration: "2 Weeks",
    tuition: 3500,
    tags: ["Entrepreneurship", "Venture Capital"],
    eligibility: ["International"],
    description: "Deep dive into the Singapore startup ecosystem and venture capital landscape.",
    special_features: ["Company founder talks", "Venture pitching", "Networking with investors"],
    noticable_facts: ["Gateway to Asian markets", "Intensive startup focus"],
    apply_link: "https://enterprise.nus.edu.sg",
  },
  {
    id: "p89",
    title: "Sydney Summer School",
    university: "University of Sydney",
    location: "Sydney, Australia",
    country: "Australia",
    level: "Undergraduate",
    category: "Summer",
    fields: ["STEM", "Humanities", "Arts"],
    format: "Offline",
    duration: "6 Weeks",
    tuition: 4000,
    tags: ["Australia", "Beach Life", "Academic"],
    eligibility: ["International"],
    description: "Study during the Australian summer (Jan-Feb) and explore the unique culture of Sydney.",
    special_features: ["Coastal field trips", "Australian history courses", "Global student mix"],
    noticable_facts: ["Southern Hemisphere schedule", "Beautiful historic campus"],
    apply_link: "https://sydney.edu.au",
  },
  {
    id: "p90",
    title: "Melbourne Summer Term",
    university: "University of Melbourne",
    location: "Melbourne, Australia",
    country: "Australia",
    level: "Undergraduate",
    category: "Summer",
    fields: ["STEM", "Humanities"],
    format: "Offline",
    duration: "4 Weeks",
    tuition: 3800,
    tags: ["Melbourne", "Urban Life", "Research"],
    eligibility: ["International"],
    description: "Intensive summer subjects in the cultural capital of Australia.",
    special_features: ["Urban exploration", "Research-led teaching", "Vibrant student life"],
    noticable_facts: ["Australia's top-ranked university", "Dynamic city campus"],
    apply_link: "https://unimelb.edu.au",
  },
  {
    id: "p91",
    title: "Oxford Executive Education",
    university: "Oxford Saïd Business School",
    location: "Oxford, UK",
    country: "UK",
    level: "Graduate",
    category: "University",
    fields: ["Business", "Leadership"],
    format: "Hybrid",
    duration: "1-2 Weeks",
    tuition: 10000,
    tags: ["Executive", "Networking", "Oxford"],
    eligibility: ["International"],
    description: "Short, high-impact leadership and business programs for experienced professionals.",
    special_features: ["Oxford faculty coaching", "Elite professional network", "Historic college stay"],
    noticable_facts: ["Global executive prestige", "High-level strategic focus"],
    apply_link: "https://sbs.ox.ac.uk",
  },
  {
    id: "p92",
    title: "INSEAD Summer Program",
    university: "INSEAD",
    location: "Fontainebleau, France",
    country: "France",
    level: "Graduate",
    category: "Summer",
    fields: ["Business"],
    format: "Offline",
    duration: "2 Weeks",
    tuition: 8000,
    tags: ["Business", "International", "MBA"],
    eligibility: ["International"],
    description: "Mini-MBA experience focused on global business management and international strategy.",
    special_features: ["Case study marathons", "Global team projects", "Forest campus experience"],
    noticable_facts: ["The Business School for the World", "Highly diverse cohort"],
    apply_link: "https://insead.edu",
  },
  {
    id: "p93",
    title: "London Business School Summer",
    university: "London Business School",
    location: "London, UK",
    country: "UK",
    level: "Graduate",
    category: "Summer",
    fields: ["Business"],
    format: "Offline",
    duration: "3 Weeks",
    tuition: 9000,
    tags: ["Finance", "London", "Elite"],
    eligibility: ["International"],
    description: "Advanced finance and management programs in the world's financial heart.",
    special_features: ["City of London visits", "Professional mentorship", "Strategic networking"],
    noticable_facts: ["Top-tier global rankings", "Premier finance focus"],
    apply_link: "https://london.edu",
  },
  {
    id: "p94",
    title: "MIT Bootcamps",
    university: "MIT",
    location: "Online / Global",
    country: "USA",
    level: "Undergraduate",
    category: "Summer",
    fields: ["Business", "STEM"],
    format: "Hybrid",
    duration: "1 Week",
    tuition: 5000,
    tags: ["Entrepreneurship", "Innovation", "MIT"],
    eligibility: ["International", "Domestic"],
    description: "Intensive, week-long programs where participants start a venture and learn the MIT way of innovating.",
    special_features: ["Extreme entrepreneurship", "Pitching to MIT faculty", "Alumni community access"],
    noticable_facts: ["High intensity 'drinking from a firehose'", "Global locations"],
    apply_link: "https://bootcamp.mit.edu",
  },
  {
    id: "p95",
    title: "Singularity University Summer",
    university: "Singularity University",
    location: "Online / Silicon Valley",
    country: "USA",
    level: "Graduate",
    category: "Summer",
    fields: ["STEM", "Business"],
    format: "Hybrid",
    duration: "2-4 Weeks",
    tuition: 12000,
    tags: ["Exponential Tech", "Future"],
    eligibility: ["International"],
    description: "Explore exponential technologies and how to use them to solve humanity's greatest challenges.",
    special_features: ["Silicon Valley network", "Future-focused curriculum", "Impact project focus"],
    noticable_facts: ["Founded by Ray Kurzweil & Peter Diamandis", "High-tech futurist focus"],
    apply_link: "https://su.org",
  },
  {
    id: "p96",
    title: "Aalto University Summer School",
    university: "Aalto University",
    location: "Espoo, Finland",
    country: "Finland",
    level: "Undergraduate",
    category: "Summer",
    fields: ["STEM", "Arts", "Business"],
    format: "Offline",
    duration: "2-3 Weeks",
    tuition: 2000,
    tags: ["Design", "Innovation", "Nordic"],
    eligibility: ["International"],
    description: "Nordic focus on design thinking, technology, and entrepreneurship.",
    special_features: ["Design Factory access", "Nordic nature trips", "Collaborative design projects"],
    noticable_facts: ["World leader in design education", "Unique interdisciplinary focus"],
    apply_link: "https://aalto.fi/summer-school",
  },
  {
    id: "p97",
    title: "TU Delft Summer School",
    university: "TU Delft",
    location: "Delft, Netherlands",
    country: "Netherlands",
    level: "Undergraduate",
    category: "Summer",
    fields: ["STEM"],
    format: "Offline",
    duration: "2 Weeks",
    tuition: 2200,
    tags: ["Water Management", "Engineering"],
    eligibility: ["International"],
    description: "Leading programs in water management, sustainable energy, and aerospace engineering.",
    special_features: ["Dike and dam visits", "Advanced lab access", "Bicycle-friendly campus"],
    noticable_facts: ["World's best in water engineering", "Historic technical university"],
    apply_link: "https://tudelft.nl",
  },
  {
    id: "p98",
    title: "KTH Summer School",
    university: "KTH Royal Institute",
    location: "Stockholm, Sweden",
    country: "Sweden",
    level: "Undergraduate",
    category: "Summer",
    fields: ["STEM"],
    format: "Offline",
    duration: "4 Weeks",
    tuition: 2500,
    tags: ["Sustainability", "Tech", "Sweden"],
    eligibility: ["International"],
    description: "Sustainability and smart city technology in one of Europe's most innovative cities.",
    special_features: ["Smart city tours", "Innovation hub visits", "Stockholm archipelago trips"],
    noticable_facts: ["Leading technical school in Sweden", "Strong sustainability focus"],
    apply_link: "https://kth.se",
  },
  {
    id: "p99",
    title: "University of Helsinki Summer",
    university: "University of Helsinki",
    location: "Helsinki, Finland",
    country: "Finland",
    level: "Graduate",
    category: "Summer",
    fields: ["Humanities", "Social Sciences"],
    format: "Offline",
    duration: "3 Weeks",
    tuition: 1800,
    tags: ["Education", "Policy", "Nordic"],
    eligibility: ["International"],
    description: "Deep dive into the Finnish education system and welfare state models.",
    special_features: ["School visits", "Policy debates", "Sauna and nature experiences"],
    noticable_facts: ["World's best education system focus", "Top-tier Nordic research"],
    apply_link: "https://helsinki.fi/summer-school",
  },
  {
    id: "p100",
    title: "Copenhagen Summer University",
    university: "University of Copenhagen",
    location: "Copenhagen, Denmark",
    country: "Denmark",
    level: "Undergraduate",
    category: "Summer",
    fields: ["STEM", "Health", "Humanities"],
    format: "Offline",
    duration: "2 Weeks",
    tuition: 2000,
    tags: ["Health", "Sustainability", "Denmark"],
    eligibility: ["International"],
    description: "Focus on global health, sustainability, and the Danish 'Hygge' lifestyle.",
    special_features: ["Global health projects", "Sustainability walks", "Danish culture workshops"],
    noticable_facts: ["Oldest university in Denmark", "Leading health research"],
    apply_link: "https://summer.ku.dk",
  },
];

export default function ProgramsPage() {
  const [search, setSearch] = useState("");
  const [tempSearch, setTempSearch] = useState("");
  const [sort, setSort] = useState("tuition_asc");
  const [selectedProgram, setSelectedProgram] = useState<Program | null>(null);
  const [isFilterOpen, setIsFilterOpen] = useState(false);
  
  // Filter States
  const [activeFields, setActiveFields] = useState<string[]>([]);
  const [activeLevels, setActiveLevels] = useState<string[]>([]);
  const [activeCategories, setActiveCategories] = useState<string[]>([]);
  const [activeFormats, setActiveFormats] = useState<string[]>([]);
  const [fundingTypes, setFundingTypes] = useState<string[]>([]);
  const [eligibility, setEligibility] = useState<string[]>([]);
  const [activeDifficulties, setActiveDifficulties] = useState<string[]>([]);
  const [activeTesting, setActiveTesting] = useState<string[]>([]);
  const [activeLanguages, setActiveLanguages] = useState<string[]>([]);
  const [location, setLocation] = useState("Any Location");

  const { saveItem, removeItem, isSaved } = useSaved();

  const fieldOptions = ["STEM", "Mathematics", "Medicine", "Humanities", "Business", "Arts", "Social Sciences", "Law", "Education", "Interdisciplinary"];
  const levelOptions = ["High School", "Undergraduate", "Graduate"];
  const formatOptions = ["Online", "Offline", "Hybrid"];
  const categoryOptions = ["Summer", "Research", "Internship", "Competition", "University"];
  const fundingOptions = ["Fully Funded", "Paid", "Free"];
  const eligibilityOptions = ["International", "Domestic"];
  const difficultyOptions = ["Beginner", "Intermediate", "Advanced"];
  const testingOptions = ["IELTS/TOEFL Required", "No Tests Needed"];
  const languageOptions = ["English Only", "Bilingual"];
  const locations = useMemo(() => ["Any Location", ...Array.from(new Set(programsData.map(p => p.country))).sort()], []);

  const tog = (arr: string[], val: string, set: React.Dispatch<React.SetStateAction<string[]>>) => {
    set(prev => prev.includes(val) ? prev.filter(x => x !== val) : [...prev, val]);
  };

  const filtered = useMemo(() => {
    let r = programsData;
    if (search) {
      const s = search.toLowerCase();
      r = r.filter(p => p.title.toLowerCase().includes(s) || p.university.toLowerCase().includes(s) || p.tags.some(t => t.toLowerCase().includes(s)));
    }
    if (activeFields.length > 0) r = r.filter(p => activeFields.some(f => p.fields.includes(f)));
    if (activeLevels.length > 0) r = r.filter(p => activeLevels.includes(p.level));
    if (activeFormats.length > 0) r = r.filter(p => activeFormats.includes(p.format));
    if (activeCategories.length > 0) r = r.filter(p => activeCategories.includes(p.category));
    if (location !== "Any Location") r = r.filter(p => p.country === location);
    if (eligibility.length > 0) r = r.filter(p => eligibility.some(e => p.eligibility.includes(e as any)));
    
    if (fundingTypes.length > 0) {
      r = r.filter(p => {
        if (fundingTypes.includes("Free") && p.tuition === 0) return true;
        if (fundingTypes.includes("Paid") && p.tuition > 0) return true;
        if (fundingTypes.includes("Fully Funded") && p.tags.some(t => t.toLowerCase().includes("funded"))) return true;
        return false;
      });
    }
    return [...r].sort((a, b) => {
      if (sort === "tuition_asc") return a.tuition - b.tuition;
      if (sort === "name_asc") return a.title.localeCompare(b.title);
      return 0;
    });
  }, [search, activeFields, activeLevels, activeFormats, activeCategories, fundingTypes, eligibility, location, sort]);

  const activeFiltersCount = activeFields.length + activeLevels.length + activeFormats.length + activeCategories.length + fundingTypes.length + eligibility.length + activeDifficulties.length + activeTesting.length + activeLanguages.length + (location !== "Any Location" ? 1 : 0);

  return (
    <>
      <PublicHeader />
      {selectedProgram && (
        <InfoModal isOpen={!!selectedProgram} onClose={() => setSelectedProgram(null)} title={selectedProgram.title} subtitle={selectedProgram.university} icon="🎓"
          image={selectedProgram.image || "https://images.unsplash.com/photo-1523050335192-ce67457e0c1e?q=80&w=1200"}
          description={selectedProgram.description} specialFeatures={selectedProgram.special_features}
          stats={[{ label: "Level", value: selectedProgram.level }, { label: "Format", value: selectedProgram.format }, { label: "Cost", value: selectedProgram.tuition === 0 ? "Free" : `$${selectedProgram.tuition.toLocaleString()}` }]}
          tips={selectedProgram.noticable_facts || ["Review prerequisites carefully.", "Prepare a strong Statement of Purpose."]} ctaLink={selectedProgram.apply_link} ctaLabel="Apply Now" />
      )}
      <main id="mainContent" style={{ paddingTop: "80px", minHeight: "100vh", background: "var(--bg-color)" }}>
        <section className={styles.heroSection}>
          <div className="container" style={{ maxWidth: "800px" }}>
            <motion.h1 initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} className="section-title gradient-text" style={{ fontSize: "clamp(2.5rem, 6vw, 5rem)", marginBottom: "1rem", fontWeight: 800 }}>Academic Programs</motion.h1>
            <motion.p initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ delay: 0.15 }} style={{ fontSize: "1.2rem", color: "var(--text-muted)", marginBottom: "3rem", fontWeight: 500 }}>
              Browse through top pre-college and university programs mapped from our Master Resource Guide.
            </motion.p>
            <div className={styles.searchBox}>
              <Search style={{ color: "#6366f1", opacity: 0.5 }} size={20} />
              <input type="text" placeholder="Search for programs, universities, or topics..." className={styles.searchInput} value={tempSearch} onChange={e => setTempSearch(e.target.value)} onKeyDown={e => e.key === "Enter" && setSearch(tempSearch)} />
              <button className={styles.searchBtn} onClick={() => setSearch(tempSearch)}>Search</button>
            </div>
          </div>
        </section>

        <section style={{ background: "var(--bg-color)" }}>
          <div className={`container ${styles.layout}`}>
            
            <div style={{ maxWidth: "1280px", width: "100%", margin: "0 auto" }}>
              <div className={styles.filterBar} onClick={() => setIsFilterOpen(!isFilterOpen)}>
                <div className={styles.filterBarLeft}>
                  <FilterIcon size={18} style={{ color: "#6366f1" }} />
                  <span className={styles.filterBarTitle}>
                    Filter {activeFiltersCount > 0 && <span className={styles.filterCount}>{activeFiltersCount}</span>}
                  </span>
                </div>
                <ChevronDown size={20} style={{ transform: isFilterOpen ? "rotate(180deg)" : "none", transition: "0.3s", color: "var(--text-muted)" }} />
              </div>

              <AnimatePresence>
                {isFilterOpen && (
                  <motion.div initial={{ height: 0, opacity: 0 }} animate={{ height: "auto", opacity: 1 }} exit={{ height: 0, opacity: 0 }} transition={{ duration: 0.3 }} style={{ overflow: "hidden" }}>
                    <div className={styles.expandedFilters}>
                      <div>
                        <span className={styles.filterSectionTitle}><FlaskConical size={12} /> Field of Study</span>
                        <div className={styles.checkGrid}>
                          {fieldOptions.map(f => (
                            <label key={f} className={styles.checkLabel}>
                              <input type="checkbox" checked={activeFields.includes(f)} onChange={() => tog(activeFields, f, setActiveFields)} />
                              {f}
                            </label>
                          ))}
                        </div>
                      </div>

                      <div>
                        <span className={styles.filterSectionTitle}><Monitor size={12} /> Program Format</span>
                        <div className={styles.checkGrid}>
                          {formatOptions.map(f => (
                            <label key={f} className={styles.checkLabel}>
                              <input type="checkbox" checked={activeFormats.includes(f)} onChange={() => tog(activeFormats, f, setActiveFormats)} />
                              {f}
                            </label>
                          ))}
                        </div>
                        <div style={{ marginTop: "1.5rem" }}>
                          <span className={styles.filterSectionTitle}><GraduationCap size={12} /> Degree Level</span>
                          <div className={styles.checkGrid}>
                            {levelOptions.map(l => (
                              <label key={l} className={styles.checkLabel}>
                                <input type="checkbox" checked={activeLevels.includes(l)} onChange={() => tog(activeLevels, l, setActiveLevels)} />
                                {l}
                              </label>
                            ))}
                          </div>
                        </div>
                      </div>

                      <div>
                        <span className={styles.filterSectionTitle}><UserCheck size={12} /> Eligibility</span>
                        <div className={styles.checkGrid}>
                          {eligibilityOptions.map(e => (
                            <label key={e} className={styles.checkLabel}>
                              <input type="checkbox" checked={eligibility.includes(e)} onChange={() => tog(eligibility, e, setEligibility)} />
                              {e} Students
                            </label>
                          ))}
                        </div>
                        <div style={{ marginTop: "1.5rem" }}>
                          <span className={styles.filterSectionTitle}><Trophy size={12} /> Program Type</span>
                          <div className={styles.checkGrid}>
                            {categoryOptions.map(c => (
                              <label key={c} className={styles.checkLabel}>
                                <input type="checkbox" checked={activeCategories.includes(c)} onChange={() => tog(activeCategories, c, setActiveCategories)} />
                                {c}
                              </label>
                            ))}
                          </div>
                        </div>
                      </div>

                      <div>
                        <span className={styles.filterSectionTitle}><Coins size={12} /> Funding & Cost</span>
                        <div className={styles.checkGrid}>
                          {fundingOptions.map(f => (
                            <label key={f} className={styles.checkLabel}>
                              <input type="checkbox" checked={fundingTypes.includes(f)} onChange={() => tog(fundingTypes, f, setFundingTypes)} />
                              {f}
                            </label>
                          ))}
                        </div>
                        <div style={{ marginTop: "1.5rem" }}>
                          <span className={styles.filterSectionTitle}><Globe size={12} /> Language & Tests</span>
                          <div className={styles.checkGrid}>
                            {languageOptions.map(l => (
                              <label key={l} className={styles.checkLabel}>
                                <input type="checkbox" checked={activeLanguages.includes(l)} onChange={() => tog(activeLanguages, l, setActiveLanguages)} />
                                {l}
                              </label>
                            ))}
                            {testingOptions.map(t => (
                              <label key={t} className={styles.checkLabel}>
                                <input type="checkbox" checked={activeTesting.includes(t)} onChange={() => tog(activeTesting, t, setActiveTesting)} />
                                {t}
                              </label>
                            ))}
                          </div>
                        </div>
                      </div>

                      <div>
                        <span className={styles.filterSectionTitle}><Trophy size={12} /> Difficulty Level</span>
                        <div className={styles.checkGrid}>
                          {difficultyOptions.map(d => (
                            <label key={d} className={styles.checkLabel}>
                              <input type="checkbox" checked={activeDifficulties.includes(d)} onChange={() => tog(activeDifficulties, d, setActiveDifficulties)} />
                              {d}
                            </label>
                          ))}
                        </div>
                        <div style={{ marginTop: "1.5rem" }}>
                          <span className={styles.filterSectionTitle}><Globe size={12} /> Location</span>
                          <select className={styles.filterSelect} value={location} onChange={e => setLocation(e.target.value)}>
                            {locations.map(l => <option key={l} value={l}>{l}</option>)}
                          </select>
                        </div>
                      </div>
                    </div>
                  </motion.div>
                )}
              </AnimatePresence>

              <div className={styles.controlsRow}>
                <span className={styles.resultsText}>Showing <strong>{filtered.length}</strong> Programs</span>
                <div className={styles.sortWrapper}>
                  <span className={styles.sortLabel}>Sort by:</span>
                  <select className={styles.filterSelect} style={{ width: "auto", padding: "0.4rem 1rem" }} value={sort} onChange={e => setSort(e.target.value)}>
                    <option value="tuition_asc">💰 Lowest Cost</option>
                    <option value="name_asc">📝 Alphabetical</option>
                  </select>
                </div>
              </div>

              <div className={styles.grid} style={{ marginTop: "2rem" }}>
                <AnimatePresence>
                  {filtered.map((prog, index) => (
                    <motion.div key={prog.id} initial={{ opacity: 0, scale: 0.95 }} animate={{ opacity: 1, scale: 1 }} transition={{ delay: index * 0.05 }} className={styles.card}>
                      <Bookmark className={`${styles.bookmarkTop} ${isSaved(prog.id) ? styles.saved : ""}`} size={20} onClick={() => { if (isSaved(prog.id)) removeItem(prog.id); else saveItem({ id: prog.id, title: prog.title, type: "Program", source: prog.university, image: prog.image }); }} fill={isSaved(prog.id) ? "currentColor" : "none"} />
                      <div className={styles.cardHeader}>
                        <div className={styles.logoWrapper}>
                          <img 
                            src={prog.logo || "https://www.google.com/s2/favicons?domain=" + prog.university.toLowerCase().replace(/ /g, "") + ".edu&sz=128"} 
                            alt={prog.title} 
                            className={styles.uniLogo}
                            style={{ maxWidth: "100%", maxHeight: "100%", objectFit: "contain" }}
                            onError={(e) => { 
                              e.currentTarget.onerror = null; 
                              e.currentTarget.src = "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='32' height='32' viewBox='0 0 24 24' fill='none' stroke='%236366f1' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'%3E%3Cpath d='M22 10v6M2 10l10-5 10 5-10 5z'/%3E%3Cpath d='M6 12v5c3 3 9 3 12 0v-5'/%3E%3C/svg%3E";
                            }} 
                          />
                        </div>
                        <div style={{ flex: 1 }}>
                          <h3 className={styles.title}>{prog.title}</h3>
                          <div className={styles.university}>{prog.university}</div>
                          <div className={styles.locationRow}><MapPin size={14} />{prog.location}</div>
                        </div>
                      </div>
                      <div className={styles.detailsGrid}>
                        <div className={styles.detailItem}><span className={styles.detailLabel}>Level</span><span className={styles.detailValue}>{prog.level}</span></div>
                        <div className={styles.detailItem}><span className={styles.detailLabel}>Format</span><span className={styles.detailValue}>{prog.format}</span></div>
                        <div className={styles.detailItem}><span className={styles.detailLabel}>Eligibility</span><span className={styles.detailValue}>{prog.eligibility.length === 2 ? "Universal" : prog.eligibility[0]}</span></div>
                        <div className={styles.detailItem}><span className={styles.detailLabel}>Cost</span><span className={styles.detailValue} style={{ color: prog.tuition === 0 ? "#10b981" : "inherit" }}>{prog.tuition === 0 ? "Free" : `$${prog.tuition.toLocaleString()}`}</span></div>
                      </div>
                      <div className={styles.tags}>
                        {prog.tags.slice(0, 3).map(t => <span key={t} className={styles.tag}>{t}</span>)}
                      </div>
                      <button className={styles.viewDetailsBtn} onClick={() => setSelectedProgram(prog)}><Sparkles size={18} /> View Details</button>
                    </motion.div>
                  ))}
                </AnimatePresence>
              </div>
            </div>

          </div>
        </section>
      </main>
    </>
  );
}